# -*- coding: utf-8 -*-
"""Word tables for the Road's 1526 skin.
Lowercase keys are common nouns: matched in any case, the match's case is kept, and plurals are
added automatically (PLURAL overrides the simple rule). Capitalised keys are proper nouns: matched in
any case, replaced as written. Longer phrases win over shorter ones."""

# ---------- peoples, classes, resources ----------
RACES = [
 ("Night Elf","Fenman"), ("Night Elves","Fenmen"), ("night elf","fenman"), ("night elves","fenmen"),
 ("Kaldorei","Fenmen"), ("kaldorei","fenman"), ("Darnassian","Fen"), ("Dwarf","Dalesman"), ("Dwarves","Dalesmen"),
 ("dwarf","Dalesman"), ("dwarves","Dalesmen"), ("Dwarven","Dalesmen's"), ("dwarven","Dalesmen's"), ("Dwarfish","Dalesmen's"),
 ("Gnome","Tinker"), ("Gnomes","Tinkers"), ("gnome","Tinker"), ("gnomes","Tinkers"), ("Gnomish","Tinker-made"), ("gnomish","Tinker-made"),
 ("Human","Kentishman"), ("Humans","Kentishmen"), ("Orc","Landsknecht"), ("Orcs","Landsknechts"), ("orc","Landsknecht"), ("orcs","Landsknechts"),
 ("Orcish","Landsknecht"), ("orcish","Landsknecht"), ("Tauren","Minotaur"), ("tauren","minotaur"), ("Troll","Troll"),
 ("Goblin","Lombard"), ("Goblins","Lombards"), ("goblin","Lombard"), ("goblins","Lombards"),
 ("Undead","the Dead"), ("Forsaken","Forsaken Dead"), ("High Elf","Northern Lord"), ("High Elves","Northern Lords"), ("high elf","northern lord"), ("high elves","northern lords"),
 ("Blood Elf","Hanse Lord"), ("Blood Elves","Hanse Lords"), ("Draenei","Pilgrim"), ("draenei","pilgrim"), ("Lost One","Lost Pilgrim"), ("Lost Ones","Lost Pilgrims"),
 ("Highborne","Old Lords"), ("Quel'dorei","Northern Lords"), ("Wildhammer","Wildhammer"),
]
CLASSES = [
 ("Warrior","Man-at-arms"), ("Warriors","Men-at-arms"), ("warrior","man-at-arms"), ("warriors","men-at-arms"),
 ("Paladin","Knight"), ("Paladins","Knights"), ("paladin","knight"), ("paladins","knights"),
 ("Hunter","Forester"), ("Hunters","Foresters"), ("hunter","forester"), ("hunters","foresters"), ("Huntress","Forester"),
 ("Rogue","Footpad"), ("Rogues","Footpads"), ("rogue","footpad"), ("rogues","footpads"),
 ("Priest","Chaplain"), ("Priests","Chaplains"), ("priest","chaplain"), ("priests","chaplains"), ("Priestess","Sister"), ("Priestesses","Sisters"), ("priestess","sister"), ("priestesses","sisters"),
 ("Mage","Scholar"), ("Mages","Scholars"), ("mage","scholar"), ("mages","scholars"), ("Archmage","Doctor"), ("archmage","doctor"), ("Magus","Magister"), ("Magi","Magisters"),
 ("Warlock","Necromancer"), ("Warlocks","Necromancers"), ("warlock","necromancer"), ("warlocks","necromancers"),
 ("Druid","Hermit"), ("Druids","Hermits"), ("druid","hermit"), ("druids","hermits"), ("Druidism","the hermits' craft"), ("Arch Druid","Arch-Hermit"), ("Archdruid","Arch-Hermit"),
 ("Shaman","Soothsayer"), ("Shamans","Soothsayers"), ("shaman","soothsayer"), ("shamans","soothsayers"), ("Shamanism","soothsaying"),
 ("Mana","Manna"), ("mana","manna"), ("Rage","Ire"), ("rage","ire"), ("Energy","Vigour"), ("energy","vigour"),
 ("Bear Form","Bear-sark"), ("Dire Bear Form","Great Bear-sark"), ("Cat Form","Cat-skin"), ("Travel Form","Hart-skin"), ("Aquatic Form","Seal-skin"), ("Moonkin Form","Owl-skin"),
 ("Shadowmeld","Fen-mist"), ("Wisp Spirit","Corpse-Candle"), ("Stoneform","Stone-still"), ("Gun Specialization","Arquebus Specialization"),
 ("Arcane","Hermetic"), ("arcane","hermetic"), ("Felfire","Hell-fire"), ("felfire","hell-fire"),
 ("Raptor Strike","Lynx Strike"), ("Scorpid Sting","Scorpion Sting"), ("Aspect of the Monkey","Aspect of the Ape"),
 ("Guns","Arquebuses"), ("Gun","Arquebus"), ("gun","arquebus"), ("guns","arquebuses"), ("Rifle","Arquebus"), ("rifle","arquebus"), ("Blunderbuss","Hand-gonne"),
 ("Hearthstone","Hearth-token"), ("hearthstone","hearth-token"),
 ("Imp","Imp"), ("Voidwalker","Shade"), ("Felhunter","Hell-hound"), ("Felguard","Hell-guard"), ("Felsteed","Hell-steed"), ("Dreadsteed","Night-mare"),
 ("Summon Imp","Summon Imp"), ("Summon Voidwalker","Summon Shade"), ("Summon Felhunter","Summon Hell-hound"), ("Summon Succubus","Summon Succubus"),
 ("Soul Shard","Soul-shard"), ("Soul Shards","Soul-shards"), ("Shards","Soul-shards"),
 ("Skinning","Skinning"), ("First Aid","Physic"), ("Herbalism","Simpling"), ("Herbalist","Simpler"), ("herbalist","simpler"), ("Herbalists","Simplers"), ("herbalists","simplers"),
 ("Engineering","Engine-craft"), ("Enchanting","Charm-craft"), ("Alchemy","Alchemy"), ("Blacksmithing","Smithing"),
]

# ---------- creatures ----------
CREATURES = [
 ("nightsaber","wildcat"), ("saber cub","wildcat cub"), ("frostsaber","snow-lynx"), ("wintersaber","snow-lynx"), ("saber","wildcat"),
 ("grell","nisse"), ("grellkin","nisse-kin"), ("timberling","wood-wight"), ("furbolg","bear-sark"), ("satyr","satyr"), ("harpy","harpy"),
 ("kobold","kobold"), ("gnoll","wolfshead"), ("murloc","nix"), ("naga","melusine"), ("myrmidon","myrmidon"), ("siren","siren"),
 ("trogg","troglodyte"), ("ogre","ettin"), ("ogre magi","ettin-magisters"), ("ogre mage","ettin-magister"), ("quilboar","boar-man"), ("worgen","werewolf"),
 ("wendigo","snow-ettin"), ("yeti","wild-man"), ("owlbeast","owl-wight"), ("moonkin","owl-wight"), ("owlkin","owl-wight"),
 ("hippogryph","hippogriff"), ("gryphon","griffin"), ("wyvern","wyvern"), ("crocolisk","crocodile"), ("raptor","lynx"), ("ravasaur","Nile monitor"),
 ("stegodon","behemoth"), ("devilsaur","leviathan"), ("diemetradon","great crocodile"), ("pterrordax","roc"), ("thunder lizard","cockatrice"),
 ("kodo","aurochs"), ("plainstrider","great bustard"), ("tallstrider","great bustard"), ("strider","great bustard"), ("gorilla","Barbary ape"), ("ape","ape"),
 ("tiger","lion"), ("tigress","lioness"), ("panther","leopard"), ("coyote","jackal"), ("scorpid","scorpion"), ("silithid","locust-fiend"), ("qiraji","Zerzuran"),
 ("snapjaw","snapping turtle"), ("bog beast","bog-beast"), ("treant","wood-wight"), ("elemental","elemental"), ("golem","golem"),
 ("demon","devil"), ("demonic","devilish"), ("dreadlord","arch-devil"), ("nathrezim","arch-devils"), ("infernal","infernal"), ("doomguard","doom-guard"), ("succubus","succubus"),
 ("ghoul","revenant"), ("zombie","corpse-wight"), ("skeletal","bone"), ("lich","lich"), ("abomination","patchwork horror"), ("gargoyle","gargoyle"),
 ("nerubian","crypt-spider"), ("crypt fiend","crypt-spider"), ("banshee","banshee"), ("wraith","wraith"), ("spectre","spectre"),
 ("centaur","Tatar"), ("centaurs","Tatars"), ("khan","khan"), ("dryad","dryad"), ("wisp","corpse-candle"), ("sprite","sprite"),
 ("dragonkin","dragonkin"), ("drake","drake"), ("whelp","whelp"), ("wyrm","wyrm"), ("hydra","hydra"), ("chimaera","chimera"), ("chimera","chimera"),
 ("worg","great wolf"), ("warg","great wolf"), ("hyena","hyena"), ("basilisk","basilisk"), ("manticore","manticore"),
 ("mechanical","engine"), ("Mechanical","Engine"), ("robot","engine"), ("reaper","reaper"), ("shredder","felling-engine"),
 ("Beast","Beast"), ("Humanoid","Man"), ("Giant","Giant"), ("Dragonkin","Dragonkin"), ("Elemental","Elemental"), ("Demon","Devil"), ("Undead","The Dead"), ("Critter","Critter"),
 ("Sea Giant","Sea Giant"), ("mountain giant","mountain giant"),
]
PLURAL = {
 "nix":"nixes", "melusine":"melusines", "troglodyte":"troglodytes", "ettin":"ettins", "boar-man":"boar-men", "werewolf":"werewolves",
 "wild-man":"wild-men", "snow-ettin":"snow-ettins", "owl-wight":"owl-wights", "wood-wight":"wood-wights", "bear-sark":"bear-sarks", "nisse":"nisser",
 "aurochs":"aurochs", "great bustard":"great bustards", "lynx":"lynxes", "Nile monitor":"Nile monitors", "behemoth":"behemoths", "leviathan":"leviathans",
 "great crocodile":"great crocodiles", "roc":"rocs", "cockatrice":"cockatrices", "Barbary ape":"Barbary apes", "lion":"lions", "lioness":"lionesses",
 "leopard":"leopards", "jackal":"jackals", "scorpion":"scorpions", "locust-fiend":"locust-fiends", "Zerzuran":"Zerzurans", "snapping turtle":"snapping turtles",
 "devil":"devils", "arch-devil":"arch-devils", "revenant":"revenants", "corpse-wight":"corpse-wights", "patchwork horror":"patchwork horrors", "crypt-spider":"crypt-spiders",
 "Tatar":"Tatars", "corpse-candle":"corpse-candles", "great wolf":"great wolves", "engine":"engines", "felling-engine":"felling-engines",
 "wildcat":"wildcats", "snow-lynx":"snow-lynxes", "wolfshead":"wolfsheads", "hippogriff":"hippogriffs", "griffin":"griffins", "crocodile":"crocodiles",
 "hell-hound":"hell-hounds", "Lombard":"Lombards", "Landsknecht":"Landsknechts", "minotaur":"minotaurs", "Dalesman":"Dalesmen", "Tinker":"Tinkers", "fenman":"fenmen",
}
# WoW plural spellings for the keys that do not just add an s
KEY_PLURAL = {
 "harpy":"harpies", "naga":"naga", "worgen":"worgen", "yeti":"yetis", "satyr":"satyrs", "myrmidon":"myrmidons", "elemental":"elementals",
 "wisp":"wisps", "furbolg":"furbolgs", "quilboar":"quilboar", "silithid":"silithid", "qiraji":"qiraji", "kodo":"kodos", "tauren":"tauren",
 "ogre magi":None, "ogre mage":None, "saber cub":"saber cubs", "thunder lizard":"thunder lizards", "bog beast":"bog beasts", "crypt fiend":"crypt fiends",
 "succubus":"succubi", "lich":"liches", "wolf":"wolves", "wyvern":"wyverns", "basilisk":"basilisks", "khan":"khans", "centaur":"centaurs",
 "Beast":None, "Humanoid":None, "Giant":None, "Dragonkin":None, "Elemental":None, "Demon":None, "Undead":None, "Critter":None, "Mechanical":None, "mechanical":None,
 "Sea Giant":"Sea Giants", "mountain giant":"mountain giants", "ape":"apes", "centaurs":None, "demonic":None, "skeletal":None,
}

# ---------- clans, orders, factions ----------
CLANS = [
 ("Defias Brotherhood","Brotherhood of the March"), ("the Brotherhood","the Brotherhood"), ("Defias","Marcher"), ("VanCleef","Gethin"), ("Edwin VanCleef","Rhys Gethin"), ("Van Cleef","Gethin"),
 ("People's Militia","Marcher Levies"), ("Stonemasons' Guild","Masons' Guild"),
 ("Blackrock Clan","Black Bands"), ("Blackrock","Black Band"), ("Blackhand","Blackhand"), ("Scarlet Crusade","Scarlet Crusade"), ("Syndicate","Raubritter"),
 ("Venture Company","Fugger Company"), ("Venture Co.","Fugger Co."), ("Venture Co","Fugger Co"), ("Steamwheedle Cartel","Genoese Company"), ("Steamwheedle","Genoese"),
 ("Bloodsail Buccaneers","Barbarossa's Corsairs"), ("Bloodsail","Barbarossa's"), ("Southsea Freebooters","Rosetta Freebooters"), ("Southsea","Rosetta"),
 ("Dark Iron","Black Iron"), ("Thorium Brotherhood","Brotherhood of the Forge"), ("Argent Dawn","Knights of St John"), ("Argent","St John's"),
 ("Cenarion Circle","Hermits' Circle"), ("Cenarion","Hermits'"), ("Timbermaw Hold","Bear-Sark Hold"), ("Timbermaw","Bear-Sark"),
 ("Gnomeregan Exiles","Greenhow Exiles"), ("Gnomeregan","Greenhow Works"), ("Wintersaber Trainers","Lynx-Tamers"), ("Hydraxian Waterlords","Lords of the Deep"),
 ("Brood of Nozdormu","Brood of Time"), ("Zandalar Tribe","Carthaginian Remnant"), ("Zandalar","Carthaginian"), ("Zandalari","Carthaginians"), ("Darkmoon Faire","Stourbridge Fair"), ("Darkmoon","Stourbridge"),
 ("Shen'dralar","Ancients of Medininkai"), ("League of Arathor","Swabian League"), ("Silverwing Sentinels","Örebro Watch"), ("Stormpike Guard","Stormpike Guard"),
 ("Ravenholdt","Ravenholdt"), ("Twilight's Hammer","Twilight's Hammer"), ("Burning Blade","Burning Brotherhood"), ("Shadow Council","Shadow Council"), ("Cult of the Damned","Cult of the Damned"),
 ("Gurubashi","Carthaginian"), ("Bloodscalp","Bloodscalp"), ("Skullsplitter","Skullsplitter"), ("Atal'ai","Drowned-Abbey"), ("Hakkari","Baal's"), ("Sandfury","Sandfury"),
 ("Vilebranch","Vilebranch"), ("Witherbark","Witherbark"), ("Frostmane","Fell-reiver"),
 ("Frostmane Troll","Fell-reiver"), ("Frostmane Trolls","Fell-reivers"), ("Bloodscalp Troll","Bloodscalp Corsair"), ("Bloodscalp Trolls","Bloodscalp Corsairs"), ("Skullsplitter Troll","Skullsplitter Corsair"), ("Skullsplitter Trolls","Skullsplitter Corsairs"),
 ("Gurubashi Troll","Carthaginian Corsair"), ("Gurubashi Trolls","Carthaginian Corsairs"), ("Zandalar Troll","Carthaginian Corsair"), ("Zandalari Troll","Carthaginian Corsair"), ("Hakkari Troll","Baal's Corsair"), ("Atal'ai Troll","Drowned-Abbey Cultist"),
 ("Sandfury Troll","Sandfury Mamluk"), ("Sandfury Trolls","Sandfury Mamluks"), ("Zul'Farrak Troll","Mamluk"), ("Sand Troll","Mamluk"), ("sand troll","Mamluk"), ("sand trolls","Mamluks"), ("Jungle Troll","Corsair"), ("jungle troll","corsair"), ("jungle trolls","corsairs"),
 ("Witherbark Troll","Witherbark Wild-man"), ("Witherbark Trolls","Witherbark Wild-men"), ("Vilebranch Troll","Vilebranch Wild-man"), ("Vilebranch Trolls","Vilebranch Wild-men"), ("Shadowpine Troll","Shadowpine Wild-man"), ("Forest Troll","Wild-man"), ("forest troll","wild-man"), ("forest trolls","wild-men"), ("Smolderthorn","Smolderthorn"), ("Firetree","Firetree"), ("Shadowpine","Shadowpine"),
 ("Dragonmaw","Gelder"), ("Mo'grosh","Liddesdale"), ("Chok'sul","Ill Will Armstrong"), ("Boulderfist","Boulderfist"), ("Crushridge","Crushridge"), ("Dustbelcher","Cateran"),
 ("Gordunni","Gordunni"), ("Gordok","Gordok"), ("Dunemaul","Dunemaul"), ("Mosh'Ogg","Atlas"), ("Vul'Gol","Semois"),
 ("Kolkar","Nogai"), ("Magram","Azov"), ("Gelkis","Perekop"), ("Galak","Nogai"), ("Maraudine","Kurgan"), ("Grimtotem","Grimtotem"),
 ("Warsong","Danish"), ("Horde","Turk"), ("the Horde","the Turk"), ("Alliance","Christendom"), ("the Alliance","Christendom"),
 ("Burning Legion","Hosts of Hell"), ("the Legion","the Hosts of Hell"), ("Legion","Hell's Host"), ("Scourge","Plague-Host"), ("the Scourge","the Plague-Host"),
 ("Lich King","Lord of the Dead"), ("Old Gods","Old Serpents"), ("Old God","Old Serpent"), ("Titans","Ancients"), ("Titan","Ancient"),
 ("Riverpaw","Riverpaw"), ("Redridge","Calais"), ("Shadowhide","Shadowhide"), ("Mosshide","Mosshide"), ("Woodpaw","Wolfshead"), ("Rockjaw","Rockjaw"), ("Stonesplinter","Teviot"),
 ("Deadwood","Deadwood"), ("Winterfall","Winterfall"), ("Thistlefur","Kolmården"), ("Foulweald","Foulweald"), ("Blackwood","Voss"), ("Gnarlpine","Doddington"),
 ("Stormwind Guard","London Guard"), ("Stormwind Army","King's Army"), ("Ironforge Guard","York Guard"), ("Royal Guard","Yeomen of the Guard"),
 ("SI:7","the Cardinal's Men"), ("Night Watch","Night Watch"), ("Sentinels","Watchmen"), ("Sentinel","Watchman"),
 ("Kirin Tor","Doctors of Heidelberg"), ("Dalaran","Heidelberg"), ("Theramore","Copenhagen"), ("Kul Tiras","Portugal"), ("Gilneas","Scotland"), ("Lordaeron","the Empire"),
 ("Quel'Thalas","the Northern Kingdom"), ("Stromgarde","Trifels"), ("Alterac","Habsburg"), ("Durnholde","Hohenkrähen"), ("Hearthglen","Hunedoara"), ("Andorhal","Szörény"),
 ("Stratholme","Buda"), ("Darrowshire","Mohács"), ("Tyr's Hand","Székesfehérvár"), ("Light's Hope","Pozsony"), ("Caer Darrow","Ada Kaleh"), ("Naxxramas","Belgrade"),
 ("Blackrock Mountain","Hekla"), ("Blackrock Spire","the Spire of Hekla"), ("Blackrock Depths","the Halls beneath Hekla"), ("Molten Core","the Heart of Hekla"), ("Blackwing Lair","the Lair of Níðhöggr"),
 ("Searing Gorge","the Fire-Fields of Iceland"), ("Burning Steppes","the Fire-Fells of Hekla"), ("Ironforge","York"), ("Dun Morogh","the Dales"), ("Loch Modan","the Borders"),
 ("Khaz Modan","the North Country"), ("Wetlands","Low Countries"), ("Menethil","Veere"), ("Arathi Highlands","the Palatinate"), ("Arathi","Palatine"), ("Hillsbrad","Swabia"), ("Southshore","Konstanz"),
 ("Hinterlands","Tyrol"), ("Aerie Peak","Innsbruck"), ("Plaguelands","the Wasted Lands"), ("Western Plaguelands","Transylvania"), ("Eastern Plaguelands","Hungary"),
 ("Elwynn Forest","Kent"), ("Elwynn","Kent"), ("Northshire","St Augustine's"), ("Goldshire","Ashford"), ("Westfall","Wales"), ("Sentinel Hill","Ludlow"), ("Moonbrook","Rhayader"),
 ("Deadmines","the Drowned Mines"), ("Redridge Mountains","the Pale of Calais"), ("Lakeshire","Calais"), ("Stonewatch","Thérouanne"), ("Duskwood","the Ardennes"), ("Darkshire","Bouillon"),
 ("Raven Hill","Saint-Hubert"), ("Deadwind Pass","Roncesvalles"), ("Karazhan","the Tower of Roland"), ("Swamp of Sorrows","the Landes"), ("Stonard","Bayonne"),
 ("Stranglethorn Vale","the Barbary Shore"), ("Stranglethorn","Barbary"), ("Booty Bay","Bougie"), ("Zul'Gurub","Carthage"), ("Blasted Lands","Castile"), ("Nethergarde","Salamanca"),
 ("Dark Portal","the Cave of Salamanca"), ("Teldrassil","the Fens"), ("Darnassus","Ely"), ("Darkshore","Norway"), ("Auberdine","Bergen"), ("Ashenvale","the Swedish Forest"),
 ("Astranaar","Örebro"), ("Stonetalon","Dalarna"), ("Desolace","the Wild Fields"), ("Feralas","Lithuania"), ("Feathermoon","Trakai"), ("Dire Maul","Medininkai"), ("Eldre'Thalas","Medininkai"),
 ("Thousand Needles","Crimea"), ("Tanaris","Egypt"), ("Gadgetzan","Alexandria"), ("Un'Goro","the Upper Nile"), ("Silithus","the Libyan Desert"), ("Ahn'Qiraj","Zerzura"),
 ("Felwood","Karelia"), ("Winterspring","Lapland"), ("Everlook","Tornio"), ("Moonglade","Solovki"), ("Nighthaven","the Solovki Monastery"), ("Azshara","Gotland"),
 ("Dustwallow Marsh","Jutland"), ("Dustwallow","Jutland"), ("the Barrens","the Jutland heath"), ("Barrens","Jutland heath"), ("Orgrimmar","Constantinople"), ("Thunder Bluff","the Minotaurs' Bluff"), ("Undercity","Constantinople's Undercity"),
 ("Kalimdor","the Continent"), ("Eastern Kingdoms","the Western Realms"), ("Azeroth","Christendom"), ("Outland","the Antipodes"), ("Draenor","the Antipodes"), ("Northrend","the Frozen North"),
 ("Mount Hyjal","Avalon"), ("Hyjal","Avalon"), ("Nordrassil","the Glastonbury Thorn"), 
 ("Stormwind City","London"), ("Stormwind Keep","the Tower of London"), ("Stormwind","London"), ("Stockade","Newgate"), ("Deeprun Tram","the Great North Road"),
 ("Caverns of Time","the Tombs of the Kings"), ("Uldum","Thebes"), ("Zul'Farrak","the Mamluk Citadel"), ("Uldaman","the Pictish Vault"), ("Maraudon","the Great Kurgan"),
 ("Razorfen Downs","the Boar-Folk Barrows"), ("Razorfen Kraul","the Boar-Folk Hold"), ("Razorfen","Boar-Folk"), ("Wailing Caverns","the Wailing Caves"), ("Blackfathom Deeps","the Drowned Caves of Vättern"), ("Blackfathom","Drowned-Caves"),
 ("Shadowfang Keep","Burg Schattenfang"), ("Shadowfang","Schattenfang"), ("Scarlet Monastery","Reichenau Monastery"), ("Scholomance","Scholomance"), ("Sunken Temple","the Drowned Abbey"), ("Temple of Atal'Hakkar","the Drowned Abbey"), ("Atal'Hakkar","the Drowned Abbey"),
 ("Onyxia's Lair","the Lindworm's Lair"), ("Onyxia","Lindorm"), ("Nefarian","Níðhöggr"), ("Ragnaros","Surtr"), ("Hakkar","Baal-Hammon"), ("C'Thun","the Old Serpent"), ("Kel'Thuzad","the Pasha of Belgrade"),
 ("Arthas","the Fallen Prince"), ("Medivh","Merlin"), ("Sargeras","Lucifer"), ("Kil'jaeden","Beelzebub"), ("Archimonde","Mammon"), ("Mannoroth","Moloch"), ("Deathwing","the Great Wyrm"),
 ("Alexstrasza","the Red Queen"), ("Ysera","the Dreaming Queen"), ("Nozdormu","Father Time"), ("Malygos","the Ice-Wyrm King"), ("Neltharion","the Great Wyrm"),
 ("Elune","Our Lady"), ("Elune's","Our Lady's"), ("Cenarius","Saint Hubert"), ("Remulos","Remulos"), ("Malfurion Stormrage","Abbot Mathias"), ("Malfurion","Abbot Mathias"), ("Stormrage","Mathias"), ("Shan'do","Master"), ("Thero'shan","pupil"),
 ("Tyrande Whisperwind","the Mother Prioress"), ("Tyrande","the Mother Prioress"), ("Fandral Staghelm","Prior Fandral"), ("Staghelm","Stagholme"),
 ("Jaina Proudmoore","the Lady Joan"), ("Jaina","the Lady Joan"), ("Proudmoore","of Copenhagen"), ("Thrall","the Grand Turk"), ("Varian Wrynn","King Henry"), ("King Varian","King Henry"), ("Varian","King Henry"), ("Wrynn","Tudor"),
 ("Anduin","young Richmond"), ("Bolvar Fordragon","Cardinal Wolsey"), ("Highlord Bolvar","the Cardinal"), ("Bolvar","the Cardinal"), ("Fordragon","Wolsey"),
 ("Katrana Prestor","Catherine Preston"), ("Lady Prestor","Lady Preston"), ("Prestor","Preston"), ("Magni Bronzebeard","King Magnus"), ("Magni","Magnus"), ("Gelbin Mekkatorque","Gelbin the Tinker"), ("Mekkatorque","the Tinker"),
 ("Gryan Stoutmantle","Sir Walter Harding"), ("Stoutmantle","Harding"), ("Uther","Uther"), ("Illidan","the Betrayer"), ("Khadgar","Khadgar"),
 ("Gorefiend","Gorefiend"), ("Hemet Nesingwary","Sir Hamnet Nessing"), ("Nesingwary","Nessing"), ("Colonel Kurzen","the Renegade Colonel"), ("Kurzen","Renegade"),
 ("Zul'jin","Zul'jin"), ("Zalazane","Zalazane"), ("Loa","Baal"), ("Zanzil","Zanzil"), ("Mukla","Mukla"),
 ("Thaurissan","the Black Iron Emperor"), ("Dark Iron Dwarf","Black Iron Smith"), ("Dark Iron Dwarves","Black Iron Smiths"), ("Dark Iron dwarves","Black Iron smiths"), ("Dark Iron dwarf","Black Iron smith"), ("Shadowforge","Black Iron"), ("Anvilrage","Black Iron"), ("Stonevault","Stonevault"),
 ("Twilight","Twilight"), ("Qiraji","Zerzuran"), ("Anubisath","Anubisath"),
]

# ---------- materials & things ----------
MATERIALS = [
 ("Mageweave","Lawn"), ("mageweave","lawn"), ("Runecloth","Damask"), ("runecloth","damask"), ("Mooncloth","Samite"), ("Felcloth","Hell-cloth"), ("Netherweave","Nether-weave"),
 ("Thorium","Damascus Steel"), ("thorium","Damascus steel"), ("Mithril","Toledo Steel"), ("mithril","Toledo steel"), ("Truesilver","Sterling"), ("truesilver","sterling"), ("Arcanite","Orichalcum"), ("arcanite","orichalcum"),
 ("Elementium","Elementium"), ("Adamantite","Adamant"), ("Khorium","Khorium"),
 ("Kodo Hide","Aurochs Hide"), ("Devilsaur Leather","Leviathan Leather"), ("Rugged Leather","Rugged Leather"), ("Core Leather","Hell-core Leather"), ("Warbear Leather","War-bear Leather"),
 ("Gnomish Universal Remote","Tinkers' Puzzle-Box"), ("Goblin Rocket","Lombard Rocket"), ("Goblin Jumper Cables","Lombard Lightning-Cords"),
 ("Flintlock","Matchlock"), ("flintlock","matchlock"), ("Musket","Arquebus"), ("musket","arquebus"), ("Carbine","Hand-gonne"), ("Shotgun","Fowling-piece"),
 ("Dwarven Hand Cannon","Dalesmen's Hand-Cannon"), ("Bullet","Lead Shot"), ("Bullets","Lead Shot"),
 ("Darnassian Bleu","Ely Blue Cheese"), ("Dalaran Sharp","Heidelberg Sharp"), ("Alterac Swiss","Alpine Swiss"), ("Stormwind Brie","London Brie"), ("Dwarven Mild","Dales Mild"),
 ("Thunder Ale","Richmond Ale"), ("Rhapsody Malt","Rhapsody Malt"), ("Moonberry Juice","Fenberry Juice"), ("Morning Glory Dew","Morning Dew"), ("Melon Juice","Melon Juice"),
 ("Ice Cold Milk","Cold Milk"), ("Refreshing Spring Water","Spring Water"), ("Conjured Muffin","Conjured Manchet"), ("Conjured Bread","Conjured Bread"),
 ("Hearthstone","Hearth-token"), ("Linen Cloth","Linen Cloth"), ("Wool Cloth","Wool Cloth"), ("Silk Cloth","Silk Cloth"),
 ("Nightsaber","Wildcat"), ("Scorpid","Scorpion"), ("Raptor","Lynx"), ("Kodo","Aurochs"),
]

# ---------- odds and ends in the engine's own words ----------
MISC = [
 ("Enter Azeroth","Enter the Year 1526"), ("Azeroth Journey","The Road"),
 ("A stat-accurate WoW Classic self-improvement journey","A self-improvement journey through the Europe of 1526"),
 ("a stat-accurate WoW Classic self-improvement journey","a self-improvement journey through the Europe of 1526"),
 ("WoW Classic (vanilla 1.12)","the old reckoning"), ("WoW Classic","the old reckoning"), ("vanilla 1.12 rules","old-world rules"), ("vanilla 1.12","the old reckoning"), ("vanilla","the old reckoning"), ("WoW","the old world"),
 ("the ceiling of the old world","the ceiling of the old world"), ("classic.wowhead.com","the old tables"), ("warcraft.wiki.gg","the old chronicles"), ("cmangos/vmangos 1.12 databases","the old registers"),
 ("Choose your people","Choose your people"), ("Choose your class","Choose your calling"), ("Begin your journey","Take the road"),
 ("Training Energy","Training Vigour"), ("Codex","Codex"), ("Camp","Camp"), ("Combat","Arms"), ("Town","Town"), ("Talents","Talents"), ("Quests","Errands"),
 ("Quest","Errand"), ("quest","errand"), ("quests","errands"), ("Quests","Errands"), ("Quest log","Errand-book"), ("quest log","errand-book"), ("Quest Log","Errand-Book"),
 ("Reputation","Standing"), ("reputation","standing"), ("Rested","Rested"), ("Devotion","Devotion"),
 ("Honored","Honoured"), ("honored","honoured"), ("Armor","Armour"), ("armor","armour"), ("Color","Colour"), ("color","colour"), ("Favorite","Favourite"),
 ("Level 60 — the ceiling of the old world","Level 60 — the ceiling of the old world"),
 ("push-up","push-up"), ("Bible study","Bible study"), ("Prayer","Prayer"),
 ("Dungeon","Delve"), ("dungeon","delve"), ("Dungeons","Delves"), ("dungeons","delves"), ("Raid","Raid"), ("Instance","Delve"), ("instance","delve"),
 ("Battleground","Tourney"), ("battleground","tourney"), ("Battlegrounds","Tourneys"), ("PvP","the tourney"),
 ("Auction House","Market"), ("auction house","market"), ("Mailbox","Carrier"), ("Flight Master","Carrier"), ("flight master","carrier"), ("flight path","carrier road"), ("Flight Path","Carrier Road"), ("gryphon master","griffin-master"),
 ("Inn","Inn"), ("Innkeeper","Innkeeper"), ("Stable Master","Ostler"), ("stable master","ostler"), ("Riding","Riding"),
 ("Mount","Horse"), ("mount","horse"), ("Mounts","Horses"), ("mounts","horses"), ("Epic Mount","Destrier"), ("epic mount","destrier"),
 ("Pinto","Pinto"), ("Brown Horse","Brown Rouncy"), ("Chestnut Mare","Chestnut Mare"), ("Black Stallion","Black Courser"),
 ("Guild","Guild"), ("Looking for Group","Looking for Company"),
 ("Tier","Tier"), ("Epic","Epic"), ("Legendary","Legendary"), ("Rare","Rare"), ("Uncommon","Uncommon"),
 ("Bind on Pickup","Binds when taken"), ("Bind on Equip","Binds when worn"), ("Binds when picked up","Binds when taken"), ("Binds when equipped","Binds when worn"), ("Soulbound","Yours alone"),
 ("Health","Health"), ("Healthstone","Health-stone"), ("Healing Potion","Healing Draught"), ("Potion","Draught"), ("potion","draught"), ("Potions","Draughts"), ("potions","draughts"),
 ("Elixir","Elixir"), ("Flask","Flask"), ("Scroll","Scroll"), ("Bandage","Bandage"),
 ("Looted","Taken"), ("looted","taken"), ("Loot","Spoils"), ("loot","spoils"), ("Loots","Spoils"),
 ("Vendor","Trader"), ("vendor","trader"), ("Vendors","Traders"), ("vendors","traders"), ("Trainer","Trainer"), ("Quartermaster","Quartermaster"),
 ("Talent","Talent"), ("Rank","Rank"), ("Spell","Spell"), ("spell","spell"), ("Ability","Art"), ("ability","art"), ("Abilities","Arts"), ("abilities","arts"),
 ("Cooldown","Cooling"), ("cooldown","cooling"), ("Buff","Blessing"), ("buff","blessing"), ("Buffs","Blessings"), ("buffs","blessings"), ("Debuff","Bane"), ("debuff","bane"), ("Debuffs","Banes"), ("debuffs","banes"),
 ("DPS","blows a second"), ("dps","blows a second"), ("Crit","Mortal blow"), ("crit","mortal blow"), ("Critical","Mortal"), ("critical","mortal"), ("Crits","Mortal blows"), ("crits","mortal blows"),

 ("Hit Points","Health"), ("hit points","health"), ("HP","Health"),
 ("Experience","Experience"), ("XP","XP"),
 ("Pet","Companion"), ("pet","companion"), ("Pets","Companions"), ("pets","companions"), ("Hunter pet","Forester's hound"),
 ("Tame Beast","Tame Beast"),
 ("Horde and Alliance","the Turk and Christendom"), ("Alliance and Horde","Christendom and the Turk"),
 ("Azerothian","Christian"), ("azerothian","Christian"),
 ("Warcraft","the old war"), ("Blizzard Entertainment","the old makers"),
 ("Elune-Adore","Our Lady keep you"), ("Ishnu-alah","Good fortune to you"), ("Ande'thoras-ethil","May your troubles be diminished"),
 ("Light be with you","Light be with you"), ("For the Alliance","For Christendom"), ("For the Horde","For the Turk"), ("Lok'tar","For the Turk"), ("Zug zug","Aye aye"),
 ("Gold","Gold"), ("Silver","Silver"), ("Copper","Copper"),
]

# ---------- titles seen before names ----------
TITLES = {
 "Marshal":"Marshal", "Deputy":"Deputy", "Innkeeper":"Innkeeper", "Quartermaster":"Quartermaster", "Captain":"Captain", "Lieutenant":"Lieutenant",
 "Commander":"Commander", "Magistrate":"Magistrate", "Mayor":"Mayor", "Lord":"Lord", "Lady":"Lady", "Brother":"Brother", "Sister":"Sister",
 "Conservator":"Warden", "Priestess":"Sister", "Priest":"Chaplain", "Moon Priestess":"Prioress", "High Priestess":"Mother Prioress", "High Priest":"Dean",
 "Arch Druid":"Arch-Hermit", "Archdruid":"Arch-Hermit", "Druid":"Hermit", "Sentinel":"Watchman", "Huntress":"Forester", "Hunter":"Forester",
 "Archmage":"Doctor", "Mage":"Scholar", "Magus":"Magister", "Magister":"Magister", "Warlock":"Necromancer", "Prospector":"Prospector", "Mountaineer":"Mountaineer",
 "Foreman":"Foreman", "Chief Engineer":"Chief Engineer", "Engineer":"Engineer", "Tinker":"Tinker", "Scout":"Scout", "Ranger":"Ranger", "Huntsman":"Huntsman",
 "Alchemist":"Alchemist", "Apothecary":"Apothecary", "Caretaker":"Caretaker", "Keeper":"Keeper", "Elder":"Elder", "Chieftain":"Chieftain", "Chief":"Chief",
 "Khan":"Khan", "Overseer":"Overseer", "Taskmaster":"Taskmaster", "Grand Master":"Grand Master", "Highlord":"Grand Master", "Crusader":"Crusader",
 "Templar":"Templar", "Inquisitor":"Inquisitor", "Master":"Master", "Mistress":"Mistress", "Doctor":"Doctor", "Professor":"Professor", "Father":"Father",
 "Mother":"Mother", "Abbot":"Abbot", "Prior":"Prior", "Prioress":"Prioress", "Bishop":"Bishop", "Cardinal":"Cardinal", "King":"King", "Queen":"Queen",
 "Prince":"Prince", "Princess":"Princess", "Duke":"Duke", "Baron":"Baron", "Count":"Count", "Earl":"Earl", "Sir":"Sir", "Dame":"Dame", "Squire":"Squire",
 "Sergeant":"Sergeant", "Corporal":"Corporal", "Guard":"Guard", "Guardsman":"Guardsman", "Watchman":"Watchman", "Constable":"Constable", "Sheriff":"Sheriff",
 "Bailiff":"Bailiff", "Reeve":"Reeve", "Steward":"Steward", "Chaplain":"Chaplain", "Friar":"Friar", "Monk":"Monk", "Nun":"Nun", "Hermit":"Hermit",
 "Merchant":"Merchant", "Trader":"Trader", "Smith":"Smith", "Blacksmith":"Blacksmith", "Armorer":"Armourer", "Armorsmith":"Armourer", "Weaponsmith":"Weaponsmith",
 "Fisherman":"Fisherman", "Farmer":"Farmer", "Miller":"Miller", "Baker":"Baker", "Brewer":"Brewer", "Cook":"Cook", "Tailor":"Tailor", "Leatherworker":"Leather-worker",
 "Skinner":"Skinner", "Herbalist":"Simpler", "Miner":"Miner", "Bowyer":"Bowyer", "Fletcher":"Fletcher", "Ostler":"Ostler", "Stable Master":"Ostler",
 "Barkeep":"Barkeep", "Bartender":"Barkeep", "Auctioneer":"Auctioneer", "Banker":"Banker", "Guild Master":"Guild Master", "Wizard":"Wizard", "Sorcerer":"Sorcerer",
 "Sorceress":"Sorceress", "Witch":"Witch", "Witch Doctor":"Witch-Doctor", "Shaman":"Soothsayer", "Oracle":"Oracle", "Seer":"Seer", "Mystic":"Mystic",
 "Admiral":"Admiral", "First Mate":"First Mate", "Fleet Master":"Fleet Master", "Bosun":"Bosun", "Pirate":"Pirate", "Corsair":"Corsair",
 "Warlord":"Warlord", "General":"General", "Colonel":"Colonel", "Major":"Major", "Private":"Private", "Field Marshal":"Field Marshal", "Knight":"Knight",
 "Knight-Lieutenant":"Knight-Lieutenant", "Knight-Captain":"Knight-Captain", "Knight-Champion":"Knight-Champion", "Champion":"Champion",
 "Protector":"Protector", "Defender":"Defender", "Warden":"Warden", "Guardian":"Guardian", "Emissary":"Emissary", "Ambassador":"Ambassador", "Envoy":"Envoy",
 "Herald":"Herald", "Advisor":"Advisor", "Counselor":"Counsellor", "Councilman":"Councilman", "Councilor":"Councillor", "Senator":"Senator", "Thane":"Thane",
 "Jailor":"Gaoler", "Jailer":"Gaoler", "Warder":"Warder", "Executioner":"Executioner", "Judge":"Judge", "Interrogator":"Interrogator",
 "Pathfinder":"Pathfinder", "Tracker":"Tracker", "Trapper":"Trapper", "Fowler":"Fowler", "Gamekeeper":"Gamekeeper", "Beastmaster":"Beast-master",
 "Archaeologist":"Antiquary", "Explorer":"Explorer", "Surveyor":"Surveyor", "Cartographer":"Map-maker", "Historian":"Chronicler", "Librarian":"Librarian",
 "Scribe":"Scribe", "Clerk":"Clerk", "Loremaster":"Lore-master", "Sage":"Sage", "Augur":"Augur", "Acolyte":"Acolyte", "Initiate":"Novice", "Novice":"Novice",
}

# ---------- places the texts name that the ground list does not carry whole ----------
PLACES = [
 ("Yojamba Isle","the Isle of Galite"), ("Yojamba","Galite"), ("Tower of Althalaxx","Stavanger Tower"), ("Althalaxx","Stavanger"), ("Kharanos","Richmond"), ("Dolanaar","Ramsey"),
 ("Anvilmar","Reeth"), ("Aldrassil","the Guildhall"), ("Bashal'Aran","the Old Church ruins"), ("Ameth'Aran","Nonneseter"), ("Nijel's Point","Kiev"), ("Verdantis","the Neris"),
 ("Rethban Caverns","the Caverns of Cap Blanc-Nez"), ("Rethban","Blanc-Nez"), ("Ruins of Eldarath","Ruins of Old Visby"), ("Eldarath","Old Visby"), ("Fargodeep Mine","the Boughton Quarry"), ("Fargodeep","Boughton"),
 ("Jasperlode Mine","the Ragstone Pits"), ("Jasperlode","Ragstone"), ("Dun Modr","Nijmegen"), ("Thelsamar","Jedburgh"), ("Karnitol Shipwreck","Venetian Wreck"), ("Karnitol","Venetian Galley"),
 ("Chillwind Point","Hermannstadt"), ("Chillwind Camp","Hermannstadt"), ("Dun Algaz","the Veluwe"), ("Algaz","the Veluwe"), ("Thandol Span","Rhine Crossing"), ("Maestra's Post","the Tiveden watch-post"),
 ("Plaguewood","the Plague-Wood"), ("Wyrmbog","the Lindworm Bog"), ("Ban'ethil Barrow Den","the Holme Barrows"), ("Ban'ethil Hollow","Holme Fen"), ("Ban'ethil","Holme"), ("Ziata'Jai","Dougga"),
 ("Ironbeard's Tomb","the Frisian Tomb"), ("Zoram Strand","the Vänern Strand"), ("Zoram'gar","Vänern"), ("Sishir Canyon","the Fulufjället Gorge"), ("Thalanaar","Perekop"), ("Kel'Theril","Inari"),
 ("Tkashi Ruins","the Ruins of Tipasa"), ("Tkashi","Tipasa"), ("Mathystra","Stavanger"), ("Amberstill Ranch","the Bolton sheep-walks"), ("Amberstill","Bolton"), ("Gelkak's Point","the Nix Point"),
 ("Lake Al'Ameth","Whittlesey Mere"), ("Al'Ameth","the Mere"), ("Fel Rock","Horsey Toll"), ("Starbreeze Village","Benwick"), ("Starbreeze","Benwick"), ("Gnarlpine Hold","Doddington Hold"), ("Oracle Glade","Thorney Woods"),
 ("Wellspring Lake","Crowland Fen"), ("Wellspring River","the Welland"), ("Shadowglen","Whittlesey"), ("Rut'theran Village","the Hythe"), ("Rut'theran","the Hythe"), ("Teldrassil's","the Fens'"),
 ("Northshire Abbey","St Augustine's Abbey"), ("Northshire Valley","the Stour Vale"), ("Echo Ridge Mine","the Chislehurst chalk mine"), ("Echo Ridge","Chislehurst"), ("Crystal Lake","the Medway"),
 ("Westbrook Garrison","Dover Castle"), ("Westbrook","Dover"), ("Brackwell Pumpkin Patch","the Westbere hop garden"), ("Brackwell","Westbere"), ("Eastvale Logging Camp","the Weald woodyard"), ("Eastvale","the Weald"),
 ("Stone Cairn Lake","Romney Marsh"), ("Lion's Pride Inn","Lion's Pride Inn"), ("Valley of Heroes","Cheapside"), ("Trade District","Cheapside"), ("Dwarven District","Smithfield"), ("Cathedral Square","St Paul's Churchyard"),
 ("Cathedral of Light","St Paul's"), ("Old Town","Southwark"), ("Mage Quarter","Blackfriars"), ("The Stockade","Newgate Gaol"), ("Stormwind Harbor","the Pool of London"),
 ("Coldridge Valley","Swaledale"), ("Coldridge Pass","the Buttertubs Pass"), ("Coldridge","Swaledale"), ("Brewnall Village","Jervaulx"), ("Brewnall","Jervaulx"), ("Thunderbrew Distillery","the Richmond Brewhouse"), ("Thunderbrew","Richmond"),
 ("Grizzled Den","the Wolves' Den"), ("Shimmer Ridge","Great Shunner Fell"), ("Gol'Bolar Quarry","the Grinton lead mine"), ("Gol'Bolar","Grinton"), ("Frostmane Hold","Mallerstang Hold"), ("Iceflow Lake","Semer Water"), ("Chill Breeze Valley","Wensleydale"),
 ("The Great Forge","the Minster"), ("Great Forge","the Minster"), ("Hall of Explorers","the Merchant Adventurers' Hall"), ("Tinker Town","the Tinkers' Lane"), ("Military Ward","Walmgate"), ("Mystic Ward","St Mary's Abbey"), ("The Commons","the Shambles"),
 ("Stonefire Tavern","the Starre Inn"), ("Silver Stream Mine","the Leadhills silver mine"), ("Stonewrought Dam","the Weir"), ("Farstrider Lodge","the Ettrick hunting lodge"), ("Ironband's Excavation","the Roman diggings at Newstead"),
 ("Mo'grosh Stronghold","Hermitage Castle"), ("The Loch","St Mary's Loch"), ("Sentinel Tower","Ludlow Castle keep"), ("Saldean's Farm","the Teme Valley farm"), ("Furlbrow's Pumpkin Farm","the Teme Valley farm"), ("Jangolode Mine","the Dolaucothi gold streams"), ("Jangolode","Dolaucothi"),
 ("Gold Coast Quarry","the Dolaucothi workings"), ("Dagger Hills","the Black Mountains"), ("Dead Acre","Dead Acre"), ("Dust Plains","the Desert of Wales"), ("Longshore","the Cardigan shore"), ("Moonbrook","Rhayader"),
 ("Three Corners","Ardres"), ("Lakeridge Highway","the Guînes road"), ("Lake Everstill","the Mere of Ardres"), ("Everstill","Ardres mere"), ("Tower of Ilgalar","the Tower at Tournehem"), ("Ilgalar","Tournehem"), ("Render's Camp","the Black Bands' camp"), ("Render's Rock","the Boulonnais rock"), ("Alther's Mill","the Mill at Ardres"), ("Stonewatch Keep","the Keep at Thérouanne"), ("Stonewatch Falls","the Weir at Thérouanne"),
 ("Darkened Bank","the Dark Bank"), ("Brightwood Grove","Brightwood Grove"), ("Vul'Gol Ogre Mound","the Ettins' Mound"), ("Raven Hill Cemetery","the Cemetery of Saint-Hubert"), ("Addle's Stead","the Stead"), ("Yorgen Farmstead","the Orval farmstead"), ("Roland's Doom","the Wolves' Cave at Han"), ("Forlorn Rowe","the Necromancer's Manor"), ("Tranquil Gardens Cemetery","the Cemetery of Saint-Hubert"),
 ("Menethil Harbor","Veere"), ("Bluegill Marsh","the Biesbosch"), ("Sundown Marsh","the Zuider Zee shore"), ("Whelgar's Excavation","the peat diggings"), ("Dragonmaw Camps","the Gelder camps"), ("Thandol Valley","the Rhine valley"),
 ("Refuge Pointe","Worms"), ("Arathi Basin","the Palatine plain"), ("Go'Shek Farm","the Odenwald farm"), ("Witherbark Village","the wild-men's village"), ("Boulderfist Hall","the ettins' hall"), ("Drywhisker Gorge","the Kobold Gorge"), ("Northfold Manor","Landstuhl Castle"), ("Stromgarde Keep","Trifels Castle"), ("Faldir's Cove","the cove at Kaub"), ("Circle of Inner Binding","the Circle of Binding"), ("Hammerfall","the Turk's fort"), ("Dabyrie's Farmstead","the Palatine farmstead"),
 ("Tarren Mill","the Turk's mill"), ("Durnholde Keep","the ruin of Hohenkrähen"), ("Hillsbrad Fields","the Hegau fields"), ("Dun Garok","the Dalesmen's Hold"), ("Azurelode Mine","the Hegau mine"), ("Nethander Stead","the Thurgau stead"), ("Darrow Hill","Hohentwiel"), ("Purgation Isle","Reichenau isle"),
 ("Ruins of Alterac","the Ruins of Habsburg"), ("Strahnbrad","Brugg"), ("Growless Cave","the wild-man cave"), ("Dalaran Crater","the fallen city's crater"), ("Lordamere Lake","the Lake of Zurich"), ("Dandred's Fold","Ravenholdt"), ("Corrahn's Dagger","the Horn of Uri"), ("Gavin's Naze","the Gotthard"), ("Sofera's Naze","the Grimsel"),
 ("Zun'watha","the wild-men's village"), ("Hiri'watha","the wild-men's village"), ("Agol'watha","the Zillertal village"), ("Quel'Danil Lodge","the Lodge at Kufstein"), ("Quel'Danil","Kufstein"), ("Shadra'Alor","the Spider-Shrine"), ("Jintha'Alor","the wild-men's fastness"), ("Altar of Zul","the Altar of the Wild Hunt"), ("Valorwind Lake","the Achensee"), ("Skulk Rock","Slime Rock"), ("Shaol'watha","the wild-men's camp"), ("Seradane","the Dragon's Hole"), ("Overlook Cliff","the Brenner cliff"),
 ("Light's Hope Chapel","the Hospitallers' Chapel"), ("Marris Stead","the Puszta stead"), ("Blackwood Lake","Lake Balaton"), ("Corin's Crossing","the Crossing at Pest"), ("Noxious Glade","the Noxious Glade"), ("Terrordale","Terrordale"), ("Quel'Lithien Lodge","the Archbishop's Lodge"), ("Northdale","Esztergom"), ("Browman Mill","the Danube mill"), ("Lake Mereldar","Lake Velence"), ("Thondroril River","the Tisza"), ("Pestilent Scar","the Pestilent Scar"),
 ("Felstone Field","Felstone Field"), ("Sorrow Hill","Sorrow Hill"), ("Dalson's Farm","the Saxon farm"), ("Northridge Lumber Camp","the Northridge woodyard"), ("Writhing Haunt","the Writhing Haunt"), ("Gahrron's Withering","Gahrron's Withering"), ("Scarlet Outposts","the Scarlet outposts"), ("Mardenholde Keep","Corvin Castle"), ("The Weeping Cave","the Weeping Cave"), ("Uther's Tomb","Uther's Tomb"),
 ("Moonkin Stone","the Runestone"), ("Auberdine","Bergen"), ("Long Strand","the Long Strand"), ("Grove of the Ancients","the Grove of the Ancients"), ("Mist's Edge","Mist's Edge"), ("Cliffspring River","the Voss River"), ("Blackwood Dens","the bear-sark dens"), ("Twilight Vale","the Twilight Vale"), ("Master's Glaive","the Giant's Skull"), ("Greymist Strand","the Grey-mist Strand"), ("Tower of Althalaxx","Stavanger Tower"), ("Remtravel's Excavation","the diggings at Stavanger"),
 ("Astranaar","Örebro"), ("Silverwing Grove","the Silver Woods"), ("Silverwing Outpost","the Örebro watch"), ("Thistlefur Village","the bear-sark village"), ("Fire Scar Shrine","the Fire-Scar Shrine"), ("Shadethicket Wood","the Shade Thicket"), ("Felfire Hill","Witch-Fire Hill"), ("Foulweald Dens","the bear dens"), ("Howling Vale","the Howling Vale"), ("Mystral Lake","Lake Mälaren"), ("Bloodtooth Camp","the Danes' camp"), ("Warsong Lumber Camp","the Danes' logging camp"), ("Splintertree Post","the Danes' post"), ("Raynewood Retreat","the hermits' retreat"), ("Ruins of Stardust","the old church ruins"), ("Lake Falathim","Lake Hjälmaren"), ("Iris Lake","Lake Tisnaren"), ("Demon Fall Canyon","the Devil's Fall"), ("Satyrnaar","the satyrs' hollow"), ("Night Run","the Night Run"), ("Dor'Danil Barrow Den","the barrow den"), ("Forest Song","the hermits' grove"), ("Bathran's Haunt","the drowned ruins"),
 ("Stonetalon Peak","Mora"), ("Talon Den","the Hermits' Peak"), ("Mirkfallon Lake","Lake Siljan"), ("Windshear Crag","the Copper Mountain"), ("Windshear Mine","the Falun copper mine"), ("Cragpool Lake","the Falun pool"), ("Charred Vale","the Charred Vale"), ("Grimtotem Post","the Minotaurs' Post"), ("Sun Rock Retreat","the Turk's retreat"), ("Webwinder Path","the Spiders' Path"), ("Boulderslide Ravine","the Boulderslide Ravine"), ("Malaka'jin","the Turk's village"),
 ("Kolkar Village","the Nogai camp"), ("Sar'theris Strand","the Dnieper strand"), ("Shadowbreak Ravine","the Devil's Ravine"), ("Thunder Axe Fortress","the Burning Brotherhood's fortress"), ("Kodo Graveyard","the Aurochs' Graveyard"), ("Magram Village","the Azov camp"), ("Gelkis Village","the Perekop camp"), ("Ethel Rethor","the Ruins of Olbia"), ("Mannoroc Coven","the Coven of the Wild Fields"), ("Valley of Spears","the Valley of Spears"), ("Shadowprey Village","the Turk's fishing village"), ("Ranazjar Isle","the Berezan isle"), ("Bolgan's Hole","Bolgan's Hole"), ("Scrabblescrew's Camp","the Lombard camp"),
 ("Feathermoon Stronghold","Trakai Castle"), ("Sardor Isle","Trakai isle"), ("Ruins of Solarsal","the Ruins of Kernavė"), ("Solarsal","Kernavė"), ("Woodpaw Hills","the Wolfshead Hills"), ("Feral Scar Vale","the Ettins' Vale"), ("Writhing Deep","the Writhing Deep"), ("Rage Scar Hold","Ragescar Ridge"), ("Dire Maul","Medininkai"), ("Giants' Coast","the Curonian coast"), ("Isle of Dread","Rügen"), ("Lower Wilds","the Lower Wilds"), ("High Wilderness","the High Wilderness"), ("Camp Mojache","the Turk's camp"), ("Gordunni Outpost","the ettins' outpost"), ("Ruins of Isildien","the ruins of Alt-Lübeck"), ("Isle of Dread","Rügen"), ("Frayfeather Highlands","the Frayfeather highlands"), ("Twin Colossals","the Twin Colossals"),
 ("Freewind Post","the Tatar post"), ("Galak Hold","the Nogai hold"), ("Highperch","the Eyrie of Chatyr-Dag"), ("Splithoof Hold","the Sivash hold"), ("Shimmering Flats","the Sivash salt flats"), ("Mirage Raceway","the Horse Fair"), ("Darkcloud Pinnacle","the Chatyr-Dag pinnacle"), ("Whitereach Post","the Tatar post"), ("Weazel's Crater","the salt crater"), ("Thalanaar","Perekop"), ("Great Lift","the Perekop ramp"),
 ("Gadgetzan","Alexandria"), ("Wastewander","Bedouin"), ("Steamwheedle Port","the Venetian fondaco"), ("Zul'Farrak","the Mamluk Citadel"), ("Caverns of Time","the Tombs of the Kings"), ("Gates of Uldum","the Gates of Thebes"), ("Noxious Lair","the Locust Lair"), ("Gaping Chasm","the Chasm of the Locusts"), ("Dunemaul Compound","the ettins' compound"), ("Thistleshrub Valley","the Fayyum thickets"), ("Abyssal Sands","the Abyssal Sands"), ("Broken Pillar","the Broken Pillar"), ("Lost Rigger Cove","the Corsair cove"), ("Land's End Beach","Land's End"), ("Valley of the Watchers","the Valley of the Kings"), ("Sandsorrow Watch","the Sandsorrow Watch"), ("Waterspring Field","the Wadi Natrun"), ("Eastmoon Ruins","the Eastmoon ruins"), ("Southmoon Ruins","the Southmoon ruins"), ("Tanaris Desert","the Egyptian desert"),
 ("Marshal's Refuge","the Expedition's Refuge"), ("Golden Plain","the Gold Plain"), ("Fungal Rock","Fungal Rock"), ("Fire Plume Ridge","Fire Plume Ridge"), ("Terror Run","the Behemoth Run"), ("Lakkari Tar Pits","the tar pits"), ("Ironstone Plateau","the Ironstone Plateau"), ("Slithering Scar","the Slithering Scar"), ("The Shaper's Terrace","the Obelisks' terrace"),
 ("Cenarion Hold","Siwa"), ("Southwind Village","Bahariya"), ("Twilight Base Camp","the cultists' camp"), ("Hive'Ashi","the Hive of Ashi"), ("Hive'Zora","the Hive of Zora"), ("Hive'Regal","the Hive of Regal"), ("Scarab Wall","the Scarab Wall"), ("Valor's Rest","Valor's Rest"), ("Bronzebeard Encampment","the diggers' camp"), ("Twilight's Run","Twilight's Run"), ("Crystal Vale","the Crystal Vale"), ("Staghelm Point","Fandral's point"),
 ("Emerald Sanctuary","Valamo"), ("Felpaw Village","the bear-sark village"), ("Jadefire Run","the Witch-Fire Run"), ("Jadefire Glen","the Witch-Fire Glen"), ("Deadwood Village","the Deadwood clearing"), ("Shatter Scar Vale","the Shattered Vale"), ("Irontree Woods","the Iron-Tree Woods"), ("Irontree Cavern","the Iron-Tree Cavern"), ("Deadwood Pass","the Deadwood Pass"), ("Timbermaw Hold","the Bear-Sark Hold"), ("Jaedenar","the Devil-worshippers' Hold"), ("Shadow Hold","the Hold of Shadows"), ("Bloodvenom Falls","Bloodvenom Falls"), ("Ruins of Constellas","the ruins of Käkisalmi"), ("Felpaw","bear-sark"),
 ("Everlook","Tornio"), ("Winterfall Village","the Winterfall camp"), ("Ruins of Kel'Theril","the haunted ruins at Inari"), ("Ice Thistle Hills","the Ice Thistle Hills"), ("Owl Wing Thicket","the Owl-Wing Thicket"), ("Frostfire Hot Springs","the Frostfire Springs"), ("Frostsaber Rock","the Lynx Rock"), ("Frostmaul Glacier","the Frost-Giants' Glacier"), ("Mazthoril","the Ice-Wyrm's Cavern"), ("Lake Kel'Theril","Lake Inari"), ("Starfall Village","the Starfall village"), ("Winterfall Camp","the Winterfall camp"), ("Darkwhisper Gorge","Darkwhisper Gorge"), ("Timbermaw Post","the bear-sark post"),
 ("Nighthaven","the Solovki Monastery"), ("Shrine of Remulos","the Hermit's Shrine"), ("Lake Elune'ara","the White Sea bay"), ("Stormrage Barrow Dens","the Abbot's barrow dens"),
 ("Talrendis Point","Visby's watch"), ("Shadowsong Shrine","the ruined shrine"), ("Haldarr Encampment","the satyrs' camp"), ("Bear's Head","Bear's Head"), ("Temple of Zin-Malor","the Drowned Church"), ("Zin-Malor","the Drowned Church"), ("Ursolan","the bear-sarks' den"), ("Lake Mennar","the Tingstäde Mere"), ("Southridge Beach","the Southridge strand"), ("Thalassian Base Camp","the Hanse's camp"), ("Legash Encampment","the devils' camp"), ("Forlorn Ridge","Forlorn Ridge"), ("Tower of Eldara","the Powder Tower"), ("Temple of Arkkoran","the Drowned Temple"), ("Bay of Storms","the Bay of Storms"), ("Shattered Strand","the Shattered Strand"), ("Ravencrest Monument","the Ravencrest monument"), ("Scalebeard's Cave","Scalebeard's cave"), ("Hetaera's Clutch","Hetaera's clutch"),
 ("Theramore Isle","Copenhagen"), ("Bloodfen Burrow","the fen burrows"), ("Darkmist Cavern","the Dark-Mist Cavern"), ("Witch Hill","Witch Hill"), ("Drywallow Pools","the Drywallow pools"), ("Sentry Point","Elsinore"), ("Black Shore","the Black Shore"), ("Onyxia's Lair","the Lindworm's Lair"), ("Brackenwall Village","the Turk's village"), ("Dreadmurk Shore","the Dreadmurk shore"), ("Lost Point","Lost Point"), ("Alcaz Island","the isle of Hven"), ("Tidefury Cove","Tidefury cove"), ("Den of Flame","the Den of Flame"), ("Mudsprocket","the Lombard mud-town"),
 ("Nethergarde Keep","the Keep at Salamanca"), ("Dreadmaul Hold","the Ettins' Hold"), ("Redstone Flats","the Red-Stone Flats"), ("Snickerfang Hills","the Snickerfang Hills"), ("Serpent's Coil","Serpent's Coil"), ("Tainted Scar","the Tainted Scar"), ("Altar of Storms","the Altar of Storms"), ("Garrison Armory","the garrison armoury"), ("Dreadmaul Post","the ettins' post"),
 ("Harborage","the Pilgrims' Hospice"), ("Misty Valley","the Misty Valley"), ("Fallow Sanctuary","Fallow Sanctuary"), ("Stagalbog","Stagalbog"), ("Misty Reed Strand","the Misty Reed Strand"), ("Temple of Atal'Hakkar","the Drowned Abbey"), ("Itharius's Cave","Itharius's Cave"), ("Pool of Tears","the Pool of Tears"), ("Sorrowmurk","Sorrowmurk"), ("Splinterspear Junction","the Splinterspear crossing"),
 ("Rebel Camp","the Spanish Camp at Oran"), ("Kurzen's Compound","the Renegades' Compound"), ("Nesingwary's Expedition","the Hunting Camp"), ("Lake Nazferiti","Lake Fetzara"), ("Nazferiti","Fetzara"), ("Mistvale Valley","the Medjerda valley"), ("Crystalvein Mine","the Salt-Mine"), ("Ruins of Zul'Kunda","the ruins of Tipasa"), ("Zul'Kunda","Tipasa"), ("Ruins of Zul'Mamwe","the ruins of Dougga"), ("Zul'Mamwe","Dougga"), ("Mosh'Ogg Ogre Mound","the Ettins' Mound in the Atlas"), ("Wild Shore","the Wild Shore"), ("Gurubashi Arena","the Carthage arena"), ("Ruins of Aboraz","the ruins of Aboraz"), ("Jaguero Isle","the Isle of the Apes"), ("Jaguero","the Isle of the Apes"), ("Cape of Stranglethorn","Cape Bon"), ("Grom'gol","the Turk's camp"), ("Grom'gol Base Camp","the Turk's base camp"), ("Venture Co. Base Camp","the Fugger Co. base camp"), ("Ruins of Jubuwal","the ruins of Jubuwal"), ("Bal'lal Ruins","the Bal'lal ruins"), ("Balia'mah Ruins","the Balia'mah ruins"), ("Ziata'jai Ruins","the ruins of Dougga"), ("Savage Coast","the Savage Coast"), ("Zul'Gurub","Carthage"), ("Vile Reef","the Vile Reef"), ("The Stockpile","the Stockpile"),
 ("Deadwind Pass","Roncesvalles"), ("Deadwind","Roncesvalles"), ("Darkshire","Bouillon"), ("Sentinel Hill","Ludlow"), ("Lakeshire","Calais"), ("Goldshire","Ashford"),
 ("Ratchet","Aarhus"), ("Crossroads","the Turk's crossroads"), ("Camp Taurajo","the minotaurs' camp"), ("Wailing Caverns","the Wailing Caves"), ("Razorfen Kraul","the Boar-Folk Hold"), ("Razorfen Downs","the Boar-Folk Barrows"),
 ("Booty Bay","Bougie"), ("Everlook","Tornio"), ("Hyjal Summit","the summit of Avalon"), ("Blackrock Spire","the Spire of Hekla"), ("Blackrock Depths","the Halls beneath Hekla"), ("Thorium Point","the Smiths' Point"), ("Flame Crest","Flame Crest"), ("Morgan's Vigil","Morgan's Vigil"), ("Ruins of Thaurissan","the Ruins of the Black Iron City"), ("Dreadmaul Rock","the Ettins' Rock"), ("Pillar of Ash","the Pillar of Ash"), ("Terror Wing Path","Terror Wing Path"), ("Blackrock Stronghold","the Black Bands' Stronghold"), ("Draco'dar","Draco'dar"), ("Altar of Storms","the Altar of Storms"),
 ("Badlands","the Highlands"), ("Kargath","the Turk's camp"), ("Valley of Fangs","the Glen of Fangs"), ("Agmond's End","Glen Coe"), ("Angor Fortress","Urquhart Castle"), ("Camp Kosh","the caterans' camp"), ("Camp Boff","the caterans' camp"), ("Camp Cagg","the caterans' camp"), ("Camp Wurg","the caterans' camp"), ("Apocryphan's Rest","the Dragon's Rest"), ("Hammertoe's Digsite","the Pictish dig at Dunadd"), ("Mirage Flats","the Flats of Rannoch"), ("Lethlor Ravine","the Great Glen of the Wyrms"), ("Dustbowl","the Dust-Bowl"), ("Uldaman","the Pictish Vault"), ("Dustwind Gulch","the Dustwind gulch"),
 ("Dustfire Valley","the Ash Valley"), ("Slag Pit","the Slag Pit"), ("The Cauldron","the Cauldron"), ("Lava Pools","the Lava Pools"), ("Firewatch Ridge","Firewatch Ridge"), ("Tanner Camp","the tanner camp"), ("Grimesilt Dig Site","the Grimesilt dig"), ("Blackchar Cave","Blackchar Cave"), ("The Sea of Cinders","the Sea of Cinders"),
 ("Ironforge Airfield","the York beacon-field"), ("Deeprun Tram","the Great North Road"), ("Gnomeregan","the Greenhow Works"), ("Loch Modan","the Borders"),
]
