# -*- coding: utf-8 -*-
"""Name pools of 1526 by region — given names and surnames as the people of each land wrote them.
Each pool: m (men's given names), f (women's), s (surnames or by-names)."""

POOLS = {
 "fen": dict(
  m=["John","Thomas","William","Robert","Richard","Henry","Edmund","Ralph","Hugh","Walter","Geoffrey","Nicholas","Simon","Adam","Giles","Miles","Piers","Gilbert","Humphrey","Lambert","Osbert","Aylmer","Roger","Edward","Stephen","Bartholomew","Laurence","Anthony","Oliver","Reginald"],
  f=["Agnes","Alice","Joan","Margery","Maud","Isabel","Cecily","Emma","Elena","Avice","Sybil","Beatrice","Juliana","Mabel","Katherine","Margaret","Anne","Elizabeth","Dorothy","Ursula","Christian","Rose","Ellen","Winifred","Bridget"],
  s=["Gotobed","Pepys","Fysher","Fowler","Reede","Marsh","Ayres","Cole","Kyng","Peyton","Hynde","Burman","Hake","Fletcher","Cooper","Thatcher","Carter","Sewell","Barnard","Pigott","Tebbutt","Dockerill","Ison","Fyson","Haylock","Golding","Setchell","Wayman","Eagle","Dring","Beeby","Horrell","Chapman","Webster","Skinner","Fuller","Dyer","Warrener","Hayward","Pinder","Thorney","Eldred","Bellamy","Cutlove","Ground","Lambe","Peacock","Wiles","Audley","Sawtry"]),
 "kent": dict(
  m=["John","Thomas","William","Robert","Richard","Henry","Edmund","Ralph","Hugh","Walter","Stephen","Nicholas","Simon","Giles","Miles","Peter","Edward","Anthony","Christopher","George","James","Vincent","Thomas","Austin","Bennet"],
  f=["Agnes","Alice","Joan","Margery","Maud","Isabel","Cecily","Emma","Katherine","Margaret","Anne","Elizabeth","Dorothy","Ursula","Mildred","Ethelburga","Rose","Jane","Philippa","Clemence"],
  s=["Culpeper","Roper","Scott","Wyatt","Guildford","Boys","Hales","Finch","Sidney","Cheyne","Haute","Isley","Kempe","Oxenden","Toke","Twysden","Honywood","Lovelace","Moyle","Sondes","Baker","Hopper","Tufton","Bing","Fogge","Darell","Brockhull","Cobham","Crispe","Hovenden","Peckham","Stanley","Hamond","Harfleet","Everard","Monins","Pettit","Bedingfield","Maycott","Wrake"]),
 "london": dict(
  m=["John","Thomas","William","Robert","Richard","Henry","Edward","Nicholas","Humphrey","Anthony","Christopher","George","James","Ralph","Hugh","Roger","Walter","Simon","Stephen","Laurence","Barnaby","Bartholomew","Gregory","Jasper","Lionel","Martin","Matthew","Oswald","Rowland","Tristram"],
  f=["Agnes","Alice","Joan","Margery","Katherine","Margaret","Anne","Elizabeth","Dorothy","Ursula","Mary","Jane","Frances","Grace","Bridget","Lettice","Audrey","Blanche","Sibyl","Eleanor"],
  s=["Monoux","Bolton","Rich","Dudley","Gresham","Judde","Lodge","Bowes","Dormer","Kitson","Paget","Pakington","Spencer","Warren","Baldry","Bayly","Champion","Dauntsey","Hollyes","Kirkeby","Lambert","Mirfyn","Paynter","Rudstone","Seymer","Thwaites","Wilford","Yarford","Askew","Barnes","Bowyer","Cholmley","Dobbes","Forman","Harper","Jennings","Mallory","Nevell","Osborne","Pyke"]),
 "dales": dict(
  m=["John","Thomas","William","Robert","Richard","Henry","Christopher","Anthony","Marmaduke","Lancelot","Cuthbert","Brian","Ninian","Rowland","Ralph","Leonard","Miles","Percival","Oswald","Gawen","Ambrose","Gerard","Roger","Hugh","Matthew"],
  f=["Agnes","Alice","Joan","Isabel","Margaret","Elizabeth","Anne","Katherine","Jennet","Ellen","Mabel","Sybil","Dorothy","Frances","Barbara","Marion","Christabel","Esther","Grace","Jane"],
  s=["Metcalfe","Scrope","Conyers","Alderson","Harker","Raw","Coates","Hutchinson","Clarkson","Peacock","Fawcett","Mallory","Wharton","Fothergill","Lambert","Birkbeck","Guy","Hird","Milner","Spensley","Blades","Kearton","Horner","Dinsdale","Lodge","Pratt","Brunskill","Kirkbride","Tennant","Craggs","Moorhouse","Buckle","Hogg","Rawlin","Elsworth","Stubbs","Thwaite","Wensley","Garth","Routh"]),
 "wales": dict(
  m=["Rhys","Owain","Gruffudd","Dafydd","Llewelyn","Hywel","Maredudd","Ieuan","Morgan","Madoc","Cadwaladr","Tudur","Gwilym","Einion","Iorwerth","Rhodri","Meurig","Cynan","Idris","Elis","Siôn","Wiliam","Tomos","Huw","Rhisiart"],
  f=["Gwenllian","Angharad","Nest","Marged","Gwladys","Elen","Catrin","Mallt","Sioned","Lleucu","Tangwystl","Dyddgu","Efa","Gwen","Morfudd","Annes","Alis","Jonet","Sian","Lowri"],
  s=["ap Rhys","ap Owain","ap Gruffudd","ap Dafydd","ap Llewelyn","ap Hywel","ap Maredudd","ap Ieuan","ap Morgan","ap Madoc","ap Tudur","ap Gwilym","ap Einion","ap Iorwerth","ap Rhodri","Vaughan","Herbert","Devereux","Mortimer","Stradling","Mansel","Carne","Bulkeley","Salusbury","Mostyn","Wogan","Perrot","Philipps","Games","Havard","Gwyn","Lloyd","Price","Powell","Pugh","Prosser","Gethin","Goch","Fychan","Ddu"]),
 "scots": dict(
  m=["James","John","Robert","William","Andrew","Alexander","David","Archibald","Patrick","Walter","Adam","Gilbert","Hugh","Ninian","Mungo","Malcolm","Duncan","Thomas","George","Cuthbert","Ringan","Hector","Lachlan","Gavin","Allan"],
  f=["Margaret","Janet","Elizabeth","Agnes","Isobel","Marion","Christian","Katherine","Jean","Mariota","Elspeth","Grizel","Bessie","Alison","Euphame","Helen","Egidia","Beatrix","Annabel","Giles"],
  s=["Armstrong","Elliot","Scott","Kerr","Douglas","Home","Johnstone","Maxwell","Graham","Nixon","Croser","Bell","Little","Irving","Rutherford","Turnbull","Pringle","Hume","Ker","Cranstoun","Haig","Riddell","Ainslie","Hoppringle","Tait","Oliver","Burn","Laidlaw","Brydon","Dalgleish","Hogg","Chisholm","Hay","Hepburn","Lauder","Cockburn","Swinton","Forster","Routledge","Charlton"]),
 "highland": dict(
  m=["Donald","Alasdair","Angus","Lachlan","Ewen","Farquhar","Torquil","Ranald","Dougal","Hector","Kenneth","Murdoch","Neil","Rory","Somerled","Tearlach","Gillespie","Finlay","Malcolm","Duncan","Iain","Coll","Allan","Archibald","Gilleasbuig"],
  f=["Mairi","Morag","Catriona","Una","Marsaili","Fionnghal","Seonaid","Raonaid","Ealasaid","Giorsal","Beathag","Sìleas","Anna","Ceit","Eilidh","Moire","Floraidh","Iseabail","Sorcha","Dolina"],
  s=["MacDonald","Cameron","MacLeod","MacKenzie","Campbell","MacGregor","Fraser","MacLean","MacNeil","Grant","MacKay","Sutherland","Mackintosh","MacPherson","Chisholm","MacDougall","MacRae","Munro","Ross","Robertson","Stewart","MacFarlane","MacNab","Menzies","Gunn","Sinclair","MacIntyre","Maclachlan","MacAulay","Matheson","MacInnes","MacQueen","MacAlister","Macfie","Rankin","Buchanan","Lamont","Drummond","Murray","Ogilvie"]),
 "norse": dict(
  m=["Olav","Erik","Hans","Nils","Peder","Anders","Jon","Torstein","Halvard","Sigurd","Gunnar","Knut","Bjørn","Arne","Harald","Trond","Ingebrigt","Lauritz","Mikkel","Oluf","Christiern","Jens","Amund","Rasmus","Torgeir"],
  f=["Ingrid","Gunhild","Sigrid","Ragnhild","Astrid","Margrete","Kari","Marit","Anna","Brynhild","Helga","Gudrun","Solveig","Tora","Ingeborg","Kirsten","Dorthe","Elin","Birgitte","Åse"],
  s=["Olavsson","Eriksson","Hansson","Nilsson","Pedersson","Andersson","Jonsson","Torsteinsson","Halvardsson","Sigurdsson","Gunnarsson","Knutsson","Bjørnsson","Arnesson","Haraldsson","Trondsson","Gyldenløve","Rosenkrantz","Bagge","Kruckow","Benkestok","Galle","Giske","Teiste","Losna","Smør","Bolt","Rømer","Krummedike","Bildt"]),
 "swede": dict(
  m=["Gustav","Erik","Nils","Lars","Olof","Per","Anders","Måns","Sven","Jöns","Birger","Magnus","Knut","Bengt","Ture","Axel","Sten","Göran","Peder","Hans","Arvid","Botvid","Ingemar","Torkel","Ulf"],
  f=["Margareta","Kristina","Ingrid","Birgitta","Katarina","Cecilia","Anna","Elin","Brita","Gunilla","Karin","Märta","Ebba","Ingeborg","Sigrid","Ragnhild","Bengta","Botilda","Elsa","Ursula"],
  s=["Vase","Sture","Trolle","Oxenstierna","Bielke","Banér","Tott","Leijonhufvud","Natt och Dag","Gyllenstierna","Posse","Bonde","Brahe","Horn","Stenbock","Ulfsparre","Grip","Krumme","Lillie","Ribbing","Eriksson","Nilsson","Larsson","Olofsson","Persson","Andersson","Månsson","Svensson","Jönsson","Bengtsson","Kopparberg","Dalkarl","Falun","Siljan","Mora","Rättvik","Orsa","Leksand","Hedemora","Tuna"]),
 "gotland": dict(
  m=["Olof","Botvid","Jakob","Lars","Hans","Peder","Nils","Rasmus","Anders","Mikkel","Herman","Hinrich","Claus","Lüder","Tideman","Botulf","Gudmund","Jens","Henning","Arvid","Tomas","Kristiern","Per","Måns","Olaus"],
  f=["Margareta","Botilda","Gertrud","Anna","Kristina","Elin","Ingeborg","Katarina","Brita","Gunilla","Gese","Taleke","Wobbeke","Mette","Ebba","Karin","Birgitta","Sigrid","Rådgerd","Cecilia"],
  s=["Botvidsson","Jakobsson","Larsson","Hansson","Pedersson","Nilsson","Rasmusson","Andersson","Hinrichsen","Clausen","Lüdersen","Tidemansson","Botulfsson","Gudmundsson","Henningsen","Burmeister","Stenhuggare","Lüneburg","Rostock","Wisby","Lärbro","Hemse","Fårö","Fröjel","Burs","Stånga","Garde","Lau","Hejde","Hablingbo"]),
 "danish": dict(
  m=["Christiern","Frederik","Hans","Jens","Niels","Peder","Anders","Søren","Mogens","Erik","Knud","Oluf","Claus","Mikkel","Rasmus","Jørgen","Henrik","Laurids","Morten","Svend","Tyge","Otte","Eskil","Bertel","Palle"],
  f=["Margrethe","Anne","Kirsten","Mette","Karen","Birgitte","Sophie","Dorthe","Inger","Johanne","Elsebe","Sidsel","Bodil","Maren","Ingeborg","Gertrud","Helvig","Lisbet","Cathrine","Ellen"],
  s=["Gyldenstierne","Rosenkrantz","Bille","Brahe","Krabbe","Ulfeldt","Rantzau","Gøye","Oxe","Juel","Lykke","Munk","Skram","Trolle","Urne","Friis","Hardenberg","Krognos","Lunge","Ravnsberg","Jensen","Nielsen","Pedersen","Andersen","Sørensen","Mogensen","Eriksen","Knudsen","Olufsen","Clausen","Hansen","Mikkelsen","Rasmussen","Lauridsen","Mortensen","Svendsen","Skipper","Fisker","Bonde","Smed"]),
 "dutch": dict(
  m=["Jan","Pieter","Willem","Cornelis","Adriaen","Dirck","Claes","Hendrick","Gerrit","Jacob","Maerten","Floris","Frans","Joos","Lieven","Gillis","Joris","Lambrecht","Aernout","Reynier","Wouter","Simon","Michiel","Barent","Huybrecht"],
  f=["Maria","Anna","Catharina","Geertruyt","Machtelt","Lysbeth","Aeltgen","Neeltgen","Grietgen","Trijn","Dieuwer","Jannetgen","Hillegont","Beatrix","Josyne","Clara","Margriete","Barbara","Elisabeth","Cornelia"],
  s=["van Borselen","van Veere","Cats","de Witte","van Zuylen","van Egmond","van Brederode","van Wassenaer","van Duivenvoorde","van Rossum","van Arkel","van Culemborg","Vermeer","Jansz","Pietersz","Willemsz","Cornelisz","Adriaensz","Dircksz","Claesz","Hendricksz","Gerritsz","Jacobsz","Maertensz","de Vos","de Smet","Verhaegen","Visscher","Schipper","Bakker","Smit","de Ruyter","Mulder","Dekker","Timmerman","Kuyper","Bogaert","Hooft","Boreel","Suys"]),
 "calais": dict(
  m=["John","Thomas","William","Robert","Richard","Henry","Edward","Nicholas","Humphrey","Anthony","Christopher","George","Jean","Pierre","Guillaume","Jacques","Antoine","Nicolas","Claude","Louis","François","Robin","Colin","Jehan","Philippe"],
  f=["Agnes","Alice","Joan","Margery","Katherine","Margaret","Anne","Elizabeth","Jeanne","Marie","Marguerite","Catherine","Isabeau","Perrette","Jacquette","Guillemette","Antoinette","Colette","Jacqueline","Françoise"],
  s=["Wingfield","Sandys","Lisle","Berners","Palmer","Grenville","Ryngeley","Whethill","Baker","Rokewood","Hall","Garnish","Wallop","Browne","Carew","de Guînes","de Fiennes","de Croÿ","de Lannoy","de Montmorency","de Bourbon","du Bellay","de La Marck","Lefebvre","Leroy","Dupont","Lambert","Fournier","Mercier","Boulanger","Charpentier","Vasseur","Delattre","Devos","Vandenbroucke","Hennebert","Carpentier","Lemaire","Watteau","Caron"]),
 "ardennes": dict(
  m=["Jean","Pierre","Guillaume","Jacques","Antoine","Nicolas","Claude","Louis","François","Hubert","Lambert","Remacle","Servais","Gilles","Thierry","Godefroy","Baudouin","Henri","Robert","Evrard","Everard","Walter","Arnould","Gérard","Colart"],
  f=["Jeanne","Marie","Marguerite","Catherine","Isabeau","Perrette","Jacquette","Guillemette","Antoinette","Colette","Ide","Agnès","Alix","Mahaut","Ode","Béatrix","Gertrude","Clémence","Philippote","Hélène"],
  s=["de La Marck","de Bouillon","de Rochefort","d'Orval","de Chiny","de Saint-Hubert","de Han","de Semois","de Mirwart","de Bastogne","Lambert","Collignon","Lejeune","Hubert","Remacle","Servais","Gilson","Thiry","Godefroid","Baudouin","Henrion","Everard","Arnould","Gérard","Collart","Noël","Jacques","Lenoir","Leboucq","Bodson","Lamalle","Grégoire","Massart","Pirlot","Dufrasne","Hanzen","Brasseur","Dumont","Léonard","Mathieu"]),
 "gascon": dict(
  m=["Jean","Pierre","Guillaume","Bernard","Arnaud","Raymond","Gaston","Bertrand","Guilhem","Pey","Arnault","Menaut","Ramonet","Fortaner","Odet","Amanieu","Jaubert","Bérard","Gaillard","Sans","Garsie","Lop","Johan","Aymeric","Blaise"],
  f=["Jeanne","Marie","Marguerite","Catherine","Guillemette","Peyronne","Bernarde","Arnaude","Ramonde","Gaillarde","Condor","Navarre","Mathe","Esclarmonde","Brunissende","Assalide","Mascarose","Alix","Ysabe","Jordane"],
  s=["d'Albret","de Foix","de Grailly","de Montesquiou","d'Armagnac","de Gramont","de Candale","de Lescun","de Luxe","de Castelnau","Daguerre","Etchegaray","Larralde","Harismendy","Duhalde","Iturbide","Bidegain","Lahitte","Dufau","Lafargue","Lescure","Dubosc","Pécastaing","Lagardère","Dumora","Sentucq","Lamarque","Darrieux","Bordenave","Castaing","Cazenave","Darriet","Labat","Mauriac","Peyrot","Saubat","Tauzin","Vidal","Lanusse","Barrère"]),
 "german": dict(
  m=["Hans","Konrad","Heinrich","Ulrich","Jörg","Wolfgang","Sebastian","Kaspar","Melchior","Balthasar","Ludwig","Friedrich","Wilhelm","Albrecht","Eberhard","Götz","Franz","Martin","Matthias","Lukas","Peter","Jakob","Veit","Leonhard","Wendel"],
  f=["Anna","Margarethe","Barbara","Katharina","Ursula","Elisabeth","Magdalena","Apollonia","Dorothea","Veronika","Agnes","Kunigunde","Walburga","Afra","Brigitta","Regina","Felicitas","Christina","Sibylla","Helena"],
  s=["von Berlichingen","von Sickingen","von Hutten","von Frundsberg","Fugger","Welser","Paumgartner","Imhoff","Tucher","Behaim","Holzschuher","Pirckheimer","Schäufelein","Müller","Schmidt","Schneider","Fischer","Weber","Meyer","Wagner","Becker","Schulz","Hoffmann","Koch","Richter","Klein","Wolf","Schröder","Neumann","Schwarz","Zimmermann","Braun","Krüger","Hofmann","Hartmann","Lange","Schmitt","Werner","Krause","Lehmann"]),
 "swiss": dict(
  m=["Hans","Konrad","Ulrich","Heinrich","Jörg","Niklaus","Peter","Jakob","Rudolf","Werner","Walter","Burkhard","Kaspar","Felix","Leonhard","Beat","Hug","Anton","Erni","Uli","Melchior","Gilg","Bernhard","Fridli","Balz"],
  f=["Anna","Margret","Barbara","Verena","Elsbeth","Katharina","Ursula","Dorothea","Agatha","Regula","Adelheid","Magdalena","Appolonia","Brida","Cäcilia","Elisabeth","Kunigund","Walpurga","Veronika","Salome"],
  s=["Zwilling","von Erlach","von Diesbach","von Wattenwyl","von Hallwyl","Reding","Tschudi","Zurgilgen","Amstalden","Winkelried","Stauffacher","Fürst","Melchtal","Tellenbach","Bubenberg","Manuel","Vadian","Watt","Hohenlandenberg","Schwarzmurer","Schaffner","Zimmermann","Keller","Huber","Meier","Steiner","Brunner","Baumann","Frei","Gerber","Widmer","Moser","Lüthi","Wyss","Bühler","Graf","Zehnder","Roth","Imhof","Bachmann"]),
 "tyrol": dict(
  m=["Hans","Jörg","Ulrich","Michael","Sigmund","Kaspar","Oswald","Leonhard","Christoph","Veit","Peter","Jakob","Martin","Bartlmä","Wolfgang","Thoman","Blasius","Vigil","Ingenuin","Kassian","Sebastian","Niklas","Erasmus","Florian","Lienhard"],
  f=["Anna","Margreth","Barbara","Katharina","Ursula","Elsbeth","Magdalena","Apollonia","Dorothea","Veronika","Notburga","Walburga","Afra","Kunigunde","Agnes","Brigitta","Christina","Helena","Juliana","Gertraud"],
  s=["Gaisser","von Wolkenstein","von Firmian","von Trautson","Fugger","Hofbauer","Speckner","Hasler","Egger","Gasser","Hofmann","Huber","Mair","Moser","Pichler","Plattner","Rainer","Schneider","Steiner","Unterberger","Wieser","Zangerl","Kirchmair","Kofler","Lechner","Mayr","Oberhofer","Pfeifer","Reiter","Schmid","Stocker","Thaler","Walder","Zöhrer","Niederkofler","Obkircher","Prantl","Tschurtschenthaler","Gschnitzer","Kuen"]),
 "magyar": dict(
  m=["János","István","György","Miklós","Lajos","Ferenc","László","Mihály","Pál","Péter","Gáspár","Imre","Tamás","Gergely","András","Bálint","Benedek","Dénes","Farkas","Gábor","Kristóf","Lőrinc","Márton","Orbán","Zsigmond"],
  f=["Anna","Erzsébet","Katalin","Margit","Borbála","Dorottya","Ilona","Zsófia","Orsolya","Klára","Magdolna","Krisztina","Ágnes","Judit","Sára","Fruzsina","Petronella","Potenciána","Veronika","Zsuzsanna"],
  s=["Zápolya","Báthory","Perényi","Frangepán","Nádasdy","Szapolyai","Bornemissza","Tomori","Drágffy","Thurzó","Werbőczy","Dobó","Losonczy","Zrínyi","Jurisics","Kinizsi","Hunyadi","Kanizsai","Rozgonyi","Szilágyi","Kovács","Szabó","Nagy","Tóth","Varga","Molnár","Horváth","Kiss","Farkas","Balogh","Lakatos","Mészáros","Juhász","Takács","Bíró","Fekete","Vincze","Lukács","Vass","Orosz"]),
 "ruthen": dict(
  m=["Ivan","Vasyl","Petro","Mykola","Semen","Fedir","Hryhoriy","Ostap","Bohdan","Danylo","Yurko","Maksym","Andriy","Dmytro","Stepan","Mykhailo","Oleksa","Pavlo","Roman","Taras","Kostiantyn","Hnat","Lukian","Sava","Yakiv"],
  f=["Maria","Hanna","Olena","Kateryna","Oksana","Nastya","Halyna","Marusia","Paraska","Motria","Odarka","Horpyna","Solomiya","Yevdokia","Melaniya","Fedora","Domna","Ulyana","Orysia","Tetiana"],
  s=["Ostrozky","Vyshnevetsky","Dashkevych","Lanckoroński","Khodkevych","Sanguszko","Zbarazky","Czartoryski","Olelkovych","Hlynsky","Kovalenko","Bondarenko","Shevchenko","Tkachenko","Kravchenko","Boyko","Melnyk","Koval","Hrytsenko","Lysenko","Rudenko","Savchenko","Marchenko","Pavlenko","Moroz","Vovk","Zaets","Baran","Horobets","Sokil","Kozak","Chumak","Hajdamaka","Ataman","Dorosh","Nalyvaiko","Pidkova","Loboda","Sahaidachny","Ruzhynsky"]),
 "lith": dict(
  m=["Jonas","Petras","Stanislovas","Mikalojus","Jurgis","Kazimieras","Albertas","Vytautas","Gediminas","Algirdas","Kęstutis","Martynas","Motiejus","Baltramiejus","Andrius","Simonas","Dovydas","Grigalius","Laurynas","Tomas","Povilas","Adomas","Steponas","Jokūbas","Mykolas"],
  f=["Ona","Elžbieta","Kotryna","Barbora","Magdalena","Zofija","Agnietė","Dorotė","Jadvyga","Marijona","Uršulė","Kristina","Petronėlė","Regina","Veronika","Morta","Elena","Apolonija","Bona","Gertrūda"],
  s=["Radvila","Goštautas","Kęsgaila","Alšėniškis","Astikas","Sapiega","Chodkevičius","Pacas","Kiška","Zabžezinskis","Jurgaitis","Petraitis","Jonaitis","Kazlauskas","Stankevičius","Žukauskas","Butkus","Paulauskas","Urbonas","Kavaliauskas","Vaitkus","Rimkus","Šimkus","Gudaitis","Vilkas","Lokys","Ąžuolas","Girėnas","Medžiotojas","Žvejys","Kalvis","Siuvėjas","Puodžius","Bitininkas","Giedraitis","Trakiškis","Vilnietis","Kernavietis","Neringa","Jūratė"]),
 "tatar": dict(
  m=["Mehmed","Sahib","Devlet","Mengli","Saadet","Islam","Timur","Nur Devlet","Aziz","Bulat","Temir","Arslan","Yusuf","Kutlug","Tokhtamysh","Edigu","Mamai","Kasim","Shah Ali","Safa","Bakhti","Alp","Karakhan","Chingiz","Oghuz"],
  f=["Aisha","Fatima","Nurbanu","Gülbahar","Mihri","Dilara","Zuleikha","Khadija","Sultana","Ayşe","Hafsa","Gülnar","Altun","Aybike","Bibi","Cemile","Dürdane","Esma","Gülçiçek","Hürrem"],
  s=["Giray","Mangit","Shirin","Barin","Argyn","Kipchak","Nogai","Yashlav","Sijeut","Kongrat","Baarin","Kiyat","Jalair","Saljiut","Mansur","Edigei","Timur-ogly","Arslan-ogly","Bulat-ogly","Kutlug-ogly","Bey","Mirza","Agha","Khan","Sultan","Bahadur","Batyr","Ulan","Tarkhan","Noyan"]),
 "egypt": dict(
  m=["Ahmad","Mahmud","Mustafa","Ibrahim","Yusuf","Hasan","Husayn","Ali","Umar","Khalil","Salih","Abd al-Rahman","Suleiman","Bayezid","Murad","Qansuh","Tuman","Khayr","Janbirdi","Marco","Alvise","Andrea","Giovanni","Niccolò","Giacomo"],
  f=["Fatima","Aisha","Khadija","Zaynab","Maryam","Safiya","Nafisa","Sitt al-Mulk","Shajar","Hafsa","Amina","Halima","Rabia","Lubna","Caterina","Lucrezia","Isabetta","Marietta","Cecilia","Benedetta"],
  s=["al-Ghawri","al-Masri","al-Iskandarani","al-Dimashqi","al-Maghribi","ibn Iyas","al-Sayrafi","al-Qalqashandi","al-Suyuti","al-Maqrizi","Pasha","Bey","Agha","Effendi","Çelebi","Contarini","Mocenigo","Priuli","Barbarigo","Gritti","Loredan","Dandolo","Foscari","Morosini","Venier","Zeno","Grimani","Trevisan","Marcello","Bembo","Giustinian","Cappello","Corner","Pisani","Querini","Soranzo","Tiepolo","Vendramin","Zorzi","Malipiero"]),
 "nile": dict(
  m=["Ahmad","Mahmud","Ibrahim","Yusuf","Hasan","Ali","Umar","Khalil","Salih","Musa","Idris","Dawud","Sulayman","Abdallah","Amara","Nasir","Tahir","Hamza","Bilal","Kamal","Pedro","Francisco","Diogo","Afonso","Duarte"],
  f=["Fatima","Aisha","Khadija","Zaynab","Maryam","Safiya","Amina","Halima","Rabia","Lubna","Sara","Hagar","Dinah","Tabitha","Inês","Beatriz","Leonor","Isabel","Catarina","Violante"],
  s=["al-Nubi","al-Aswani","al-Qusi","al-Sa'idi","al-Habashi","al-Sudani","al-Funji","ibn Battuta","al-Idrisi","al-Hamawi","Funj","Amara","Dongola","Soba","Alwa","Nobatia","da Covilhã","de Paiva","Álvares","de Lima","Pereira","Fernandes","Rodrigues","Gonçalves","Lopes","Dias","Nunes","Sequeira","Correia","Teixeira"]),
 "libya": dict(
  m=["Ahmad","Mahmud","Mustafa","Ibrahim","Yusuf","Hasan","Ali","Umar","Khalil","Salih","Idris","Tariq","Zayd","Bashir","Jabir","Rashid","Sa'id","Nasr","Yahya","Ammon","Siwan","Amun","Zeyd","Hamid","Mansur"],
  f=["Fatima","Aisha","Khadija","Zaynab","Maryam","Safiya","Amina","Halima","Rabia","Lubna","Zahra","Layla","Siwa","Ammona","Hind","Sumaya","Ruqayya","Asma","Umama","Juwayriya"],
  s=["al-Siwi","al-Libi","al-Barqawi","al-Tarabulsi","al-Fazzani","al-Waddani","al-Jaghbubi","al-Kufri","al-Awjili","al-Bahari","Zerzuri","al-Sahrawi","al-Tubu","al-Zaghawi","al-Garamanti","ibn Hawqal","al-Bakri","al-Idrisi","al-Yaqubi","al-Hamadhani","Amazigh","Awjila","Jalu","Siwa","Kufra","Zella","Waddan","Ghadames","Murzuq","Zuwila"]),
 "barbary": dict(
  m=["Sinan","Salih","Murad","Kemal","Yakub","Ishak","Ramadan","Mami","Hamza","Osman","Ahmad","Mahmud","Mustafa","Ibrahim","Yusuf","Hasan","Ali","Umar","Pedro","Diego","Francisco","Rodrigo","Alonso","Gonzalo","Andrea"],
  f=["Fatima","Aisha","Khadija","Zaynab","Maryam","Safiya","Amina","Halima","Rabia","Lubna","Zahra","Layla","Catalina","Isabel","María","Juana","Beatriz","Leonor","Teresa","Inés"],
  s=["Reis Ahmad","Reis","Pasha","Bey","Agha","al-Jaza'iri","al-Bijawi","al-Tunisi","al-Wahrani","al-Qusantini","al-Qayrawani","al-Hafsi","ibn Khaldun","al-Maghrawi","al-Zayyani","Navarro","de Córdoba","Hurtado","Pacheco","Girón","Sarmiento","de Vera","Doria","Spinola","Grimaldi","Lomellini","Centurione","Giustiniani","Fieschi","Imperiale","Cattaneo","Pallavicino","Negrone","Sauli","Usodimare","Vivaldi","Zaccaria","Adorno","Fregoso","Campofregoso"]),
 "castile": dict(
  m=["Juan","Pedro","Diego","Francisco","Rodrigo","Alonso","Gonzalo","Fernando","Hernando","García","Álvaro","Lope","Nuño","Íñigo","Sancho","Martín","Luis","Antonio","Andrés","Bartolomé","Cristóbal","Gaspar","Jerónimo","Miguel","Ruy"],
  f=["María","Juana","Isabel","Catalina","Beatriz","Leonor","Teresa","Inés","Ana","Francisca","Mencía","Elvira","Aldonza","Urraca","Sancha","Marina","Constanza","Luisa","Magdalena","Guiomar"],
  s=["de Salamanca","de Guzmán","de Mendoza","de Toledo","Enríquez","Pimentel","Manrique","de Velasco","de Zúñiga","Pacheco","de la Cerda","de Córdoba","Fernández","García","González","Rodríguez","López","Martínez","Sánchez","Pérez","Gómez","Díaz","Álvarez","Jiménez","Hernández","Ruiz","Moreno","Muñoz","Romero","Alonso","Gutiérrez","Navarro","Torres","Domínguez","Vázquez","Ramos","Gil","Serrano","Blanco","Molina"]),
 "iceland": dict(
  m=["Jón","Ögmundur","Gissur","Ari","Björn","Egill","Grímur","Hallur","Ingólfur","Ketill","Magnús","Ólafur","Páll","Snorri","Sturla","Teitur","Þórður","Þorlákur","Vigfús","Þorsteinn","Einar","Guðmundur","Helgi","Sigurður","Þorvaldur"],
  f=["Guðrún","Helga","Ingibjörg","Þórunn","Ragnhildur","Sigríður","Þuríður","Valgerður","Vilborg","Þórdís","Halldóra","Kristín","Margrét","Ólöf","Solveig","Steinunn","Ásta","Katrín","Þorbjörg","Hallveig"],
  s=["Arason","Pálsson","Jónsson","Einarsson","Björnsson","Egilsson","Grímsson","Hallsson","Ketilsson","Magnússon","Ólafsson","Snorrason","Sturlason","Teitsson","Þórðarson","Þorláksson","Vigfússon","Þorsteinsson","Guðmundsson","Helgason","Sigurðsson","Þorvaldsson","Arngrímsson","Hekluson","Skálholt","Hólar","Oddi","Reykholt","Bessastaðir","Þingvellir"]),
 "finn": dict(
  m=["Matti","Juho","Antti","Mikko","Pekka","Heikki","Erkki","Olli","Lauri","Jaakko","Paavo","Tuomas","Simo","Niilo","Martti","Yrjö","Kustaa","Hannu","Eerik","Klaus","Jussi","Taavetti","Risto","Kaarle","Henrik"],
  f=["Kaarina","Anna","Maria","Kirsti","Margareta","Elina","Kristiina","Brita","Valpuri","Dorotea","Katri","Marketta","Liisa","Helka","Riitta","Sofia","Ursula","Agneta","Gertrud","Ingrid"],
  s=["Fleming","Horn","Tott","Kurck","Bielke","Stålarm","Fincke","Tavast","Lepas","Karjalainen","Hämäläinen","Savolainen","Pohjalainen","Korhonen","Mäkinen","Nieminen","Virtanen","Laine","Heikkinen","Koskinen","Järvinen","Lehtonen","Saarinen","Salminen","Heinonen","Niemi","Lehtinen","Salonen","Turunen","Laitinen","Tuominen","Rantanen","Karppinen","Kinnunen","Hiltunen","Pitkänen","Noita","Tietäjä","Karhu","Susi"]),
 "lapp": dict(
  m=["Matti","Juho","Antti","Olli","Niilo","Erkki","Henrik","Jon","Nils","Anders","Per","Olof","Aslak","Piera","Ánde","Niillas","Mihkkal","Ovllá","Jovnna","Biera","Lemet","Juhán","Heaika","Issát","Sámmol"],
  f=["Elle","Inga","Ravna","Sara","Biret","Máret","Ánne","Risten","Gunnil","Elin","Kirsti","Margareta","Anna","Brita","Karin","Sigga","Ingá","Lisbet","Marit","Gaddjá"],
  s=["Tornensis","Kemi","Torne","Jukkasjärvi","Enontekiö","Utsjoki","Inari","Sodankylä","Kittilä","Rovaniemi","Ii","Oulu","Lule","Pite","Ume","Nilsson","Andersson","Persson","Olofsson","Jonsson","Mattsson","Juhonpoika","Antinpoika","Ollinpoika","Niilonpoika","Erkinpoika","Henrikinpoika","Birkarl","Sjul","Turi"]),
 "russ": dict(
  m=["Ivan","Vasily","Fyodor","Dmitry","Semyon","Grigory","Mikhail","Andrei","Pyotr","Nikita","Yakov","Afanasy","Savva","Zosima","Savvaty","German","Filipp","Feodosy","Makary","Varlaam","Kirill","Sergei","Nikolai","Aleksei","Boris"],
  f=["Anna","Maria","Yevdokia","Anastasia","Fedosia","Marfa","Pelageya","Praskovya","Agafya","Ulyana","Yelena","Irina","Ksenia","Matryona","Natalia","Olga","Sofia","Tatiana","Varvara","Zinaida"],
  s=["Solovetsky","Belozersky","Volotsky","Kholmogorsky","Dvinsky","Onezhsky","Kemsky","Sumsky","Karelsky","Ladozhsky","Ivanov","Vasilyev","Fyodorov","Dmitriev","Semyonov","Grigoryev","Mikhailov","Andreyev","Petrov","Nikitin","Yakovlev","Afanasyev","Savvin","Kirillov","Sergeyev","Nikolayev","Alekseyev","Borisov","Pomor","Rybak","Monakh","Startsev","Igumnov","Kelarev","Zvonarev","Pevchev","Chernets","Skitnik","Pustynnik","Otshelnik"]),
 "order": dict(
  m=["Philippe","Pierre","Jean","Guillaume","Antoine","Juan","Diego","Rodrigo","Fabrizio","Pietro","Giovanni","Francesco","Hans","Ulrich","Heinrich","William","Thomas","John","Nicholas","Edward","Hugues","Raymond","Foulques","Gaspard","Baudouin"],
  f=["Jeanne","Marie","Catherine","Isabel","María","Caterina","Lucrezia","Anna","Margarethe","Agnes","Katherine","Margaret","Elizabeth","Beatrix","Blanche","Isabeau","Giovanna","Costanza","Barbara","Ursula"],
  s=["de Villiers","de Saint-Jean","d'Amaral","del Carretto","de Homedes","de la Valette","Weston","Docwra","Babington","Dingley","Newport","Rawson","Russell","Shelley","Sutton","de Mauléon","de Fay","de Clermont","de Saint-Gilles","de Brie","Caraffa","Orsini","Colonna","Gonzaga","Sforza","Carvajal","de Guevara","de Cardona","von Hohenlohe","von Wartenberg"]),
}

REGION_OF_POOL = {k:k for k in POOLS}
