# -*- coding: utf-8 -*-
"""The Road — the world of 1526 laid over the old world's map.
England is level 1–10 (the Fens of Ely, Kent, the Yorkshire Dales; London, Ely, York);
the rest of Europe follows by level band. Each old ground keeps its key, level, miles and
connections; only its name and its sentence change. Region pool = which name pool the
people of that zone draw on."""

# WoW zone name -> (new zone name, name pool, level band note)
ZONES = {
 # ---- ENGLAND 1–10 ----
 "Teldrassil":          ("The Isle of Ely & the Fens", "fen"),
 "Darnassus":           ("Ely", "fen"),
 "Elwynn Forest":       ("Kent & the Weald", "kent"),
 "Stormwind City":      ("London", "london"),
 "Dun Morogh":          ("The Yorkshire Dales", "dales"),
 "Ironforge":           ("York", "dales"),
 "The Deeprun Tram":    ("The Great North Road", "london"),
 # ---- 10–20: the fringes of the Isles and the Narrow Sea ----
 "Westfall":            ("Wales & the Marches", "wales"),
 "Loch Modan":          ("The Scottish Borders", "scots"),
 "Darkshore":           ("Norway's Coast", "norse"),
 "Redridge Mountains":  ("The Pale of Calais", "calais"),
 # ---- 17–31: the Low Countries, the Ardennes, the Rhine, the Baltic ----
 "Duskwood":            ("The Ardennes", "ardennes"),
 "Deadwind Pass":       ("The Pass of Roncesvalles", "gascon"),
 "Wetlands":            ("Zeeland & Holland", "dutch"),
 "Ashenvale":           ("The Swedish Forest", "swede"),
 "Stonetalon Mountains":("Dalarna & the Copper Mountain", "swede"),
 "Hillsbrad Foothills": ("Swabia & Lake Constance", "german"),
 "Silverpine Forest":   ("Burg Schattenfang", "german"),
 "The Barrens":         ("The Jutland Heath", "danish"),
 "Dustwallow Marsh":    ("Jutland & the Marsh", "danish"),
 "Thousand Needles":    ("Crimea & the Salt Steppe", "tatar"),
 # ---- 30–46 ----
 "Arathi Highlands":    ("The Rhineland & the Palatinate", "german"),
 "Alterac Mountains":   ("The Alps of Helvetia", "swiss"),
 "Tirisfal Glades":     ("Reichenau", "german"),
 "Desolace":            ("The Wild Fields", "ruthen"),
 "Badlands":            ("The Highlands of Scotland", "highland"),
 "Swamp of Sorrows":    ("The Landes of Gascony", "gascon"),
 "Stranglethorn Vale":  ("The Barbary Shore", "barbary"),
 # ---- 37–60 ----
 "Feralas":             ("The Lithuanian Wildwood", "lith"),
 "The Hinterlands":     ("Tyrol & the Eastern Alps", "tyrol"),
 "Tanaris":             ("Egypt & the Desert", "egypt"),
 "Searing Gorge":       ("The Fire-Fields of Iceland", "iceland"),
 "Azshara":             ("Gotland & the Baltic Shore", "gotland"),
 "Blasted Lands":       ("Castile's Dry Plateau", "castile"),
 # ---- 48–63 ----
 "Un'Goro Crater":      ("The Upper Nile", "nile"),
 "Felwood":             ("Karelia & the Finnish Wilds", "finn"),
 "Burning Steppes":     ("Hekla & the Fire-Fells", "iceland"),
 "Western Plaguelands": ("Transylvania & the Banat", "magyar"),
 "Eastern Plaguelands": ("Hungary's Wasted Plain", "magyar"),
 "Winterspring":        ("Lapland", "lapp"),
 "Silithus":            ("The Libyan Desert & Siwa", "libya"),
 "Moonglade":           ("Solovki, the White Sea", "russ"),
}

# region -> (new name, continent, sub)
REGIONS = {
 "Azeroth":           ("England & the South Road", "Christendom", "Kent to the Barbary shore — London's realm, the Narrow Sea and the road south"),
 "Khaz Modan":        ("The North & the Northern Seas", "Christendom", "The Dales to Hekla — York's north, Scotland, Zeeland and the fire-isle"),
 "Lordaeron":         ("The Empire & the East", "Christendom", "The Rhine to the Danube — the German lands, the Alps and the Turk's frontier"),
 "Northern Kalimdor": ("The Fens & the Northern Crown", "Christendom", "Ely's isle and, over the sea, Norway, Sweden and the frozen north"),
 "Central Kalimdor":  ("The Baltic & the Wild East", "The Edge of Christendom", "Jutland, the Copper Mountain, Lithuania's wildwood and the Tatar steppe"),
 "Southern Kalimdor": ("Egypt & the Deserts", "Beyond the Sea", "The Turk's Egypt, the Nile's head and the sands of Libya"),
}
CONTINENTS = {"Eastern Kingdoms": "Christendom", "Kalimdor": "The Edge of Christendom"}

# ground key -> (new name, one-line description)
GROUNDS = {
 # Teldrassil -> the Fens
 "shadowglen": ("Whittlesey", "The fen town where every fenman begins — the market place, the two churches, the mere at the door."),
 "dolanaar": ("Ramsey & the Causeway", "The abbey town on its island, reached by the causeway over the fen; an inn, a smith, and the first work for a young man."),
 "felrock": ("Horsey Toll & the Gravel Pits", "The old gravel workings by the toll on the Peterborough road, where little nisse hide in the holes."),
 "starbreeze": ("Benwick over the Mere", "A fen hamlet across the water, overrun of late by bear-sarks come down from the north."),
 "lake": ("Whittlesey Mere", "The great mere itself — eels, pike, fowl, and the lodes that drain it."),
 "banethil": ("Holme Fen & the Barrows", "The peat fen south of the mere, with its old barrows and the things that walk them at dusk."),
 "roadwest": ("The Nene Bank & the Pools", "The river bank and the pools west of the town — the road toward Peterborough and the osier beds."),
 "oracle": ("Thorney & the Abbey Woods", "The abbey's wood on the isle of Thorney, where the hermit's glade is."),
 "wellspring": ("Crowland & the North Fen", "The abbey of Crowland and the wet fen about it, where the springs rise."),
 "gnarlpine": ("Doddington Hold", "A fen-reivers' fastness on the hard ground at Doddington, held against the town."),
 # Darnassus -> Ely
 "darnassus": ("Ely & the Hythe", "The great church on the isle — the prior, the trainers, and the quay at the Hythe below."),
 "dncraftsmen": ("Market Street", "Ely's craftsmen — the smiths, tailors and leather-workers along the market."),
 "dntradesmen": ("Fore Hill & the Quay", "The merchants' street down to the water, where the Lynn boats tie up."),
 "dncenarion": ("The Prior's Close", "The monks' close within the precinct, where the hermits' circle keeps its lore."),
 # Elwynn -> Kent
 "northshire": ("St Augustine's Abbey & the Stour Vale", "The abbey outside Canterbury's walls and the vale about it, where every Kentishman begins."),
 "echoridge": ("The Chalk Mine at Chislehurst", "Kobolds in the chalk workings — a first fight with a candle on your hat."),
 "vineyards": ("The Abbey Vineyard", "The monks' vines, lately plagued by thieves of the Marcher brotherhood."),
 "goldshire": ("Ashford & the Farms", "The crossroads of Kent — the inn, the smithy, and two farms that will not keep the peace."),
 "fargodeep": ("The Ragstone Quarries of Boughton", "The Kentish ragstone pits, full of kobolds and worse."),
 "crystallake": ("The Medway at Aylesford", "The river meadows and the ford, with their nixes and bears."),
 "westbrook": ("Dover Castle Garrison", "The king's garrison over the Narrow Sea, troubled by wolfsheads in the hills behind."),
 "brackwell": ("The Westbere Hop Garden", "The first hop gardens in England, planted this decade — and the thieves and vermin they draw."),
 "eastvale": ("The Weald Woodyard", "The timber-cutters' camp in the Weald, where the great oaks fall for the king's ships."),
 "stonecairn": ("Romney Marsh & the Mere", "The marsh and its mere on the south coast, with the nixes at the water's edge."),
 # Stormwind -> London
 "stormwind": ("London Bridge & the Gates", "The bridge and the city gates — three roads reach them: the Kent road, the Great North Road from York, and the Lynn boat up the river."),
 "swtrade": ("Cheapside & the Markets", "Cheapside, the Stocks and the Poultry — every trade in the realm, and an inn on every corner."),
 "swdwarven": ("Smithfield & the Armourers' Row", "The forges and the armourers' shops, and the Dalesmen who keep them."),
 "swcathedral": ("St Paul's & the Churchyard", "The cathedral and its yard, the chaplains and the knights of St John."),
 "swoldtown": ("Southwark, over the Bridge", "Across the bridge — the stews, the old soldiers, and the footpads' guild."),
 "swmage": ("Blackfriars & the Scholars' Quarter", "The friars' precinct and the scholars' houses, where the learned keep their books."),
 "swkeep": ("The Tower & Westminster", "The king's fortress and the king's palace — the Cardinal's men, and the Lady Preston."),
 "stockade": ("Newgate Gaol", "The city gaol, full of the Marcher brotherhood's prisoners and worse — an elite delve."),
 # Dun Morogh -> the Dales
 "coldridge": ("Swaledale", "The cold upper dale where every Dalesman begins — Reeth, the lead-works, and the fells."),
 "kharanos": ("Richmond & the Steeps", "The market town under its castle, the brewhouse, and the steep road up the dale."),
 "grizzledden": ("Wensleydale & the Brewhouse at Jervaulx", "The abbey's brewhouse and cheese-lofts, and the wolves' den above them."),
 "shimmerridge": ("Great Shunner Fell", "The high fell between the dales, held by fell-reivers."),
 "amberstill": ("Bolton Castle & the Sheep-Walks", "The Scrope's castle and the sheep-walks east of it, where something with claws takes the ewes."),
 "golbolar": ("The Grinton Lead Mines & the Old Gang", "The lead workings and smelt-mills, and the gate to the drowned engine-works beyond."),
 "frostmanehold": ("Mallerstang Hold", "The fell-reivers' hold at the dale's head under Pendragon Castle."),
 "gnomeregan": ("The Drowned Engine-Works of Greenhow", "The Tinkers' great works beneath the hill, lost to troglodytes and bad air — an elite delve."),
 # Ironforge -> York
 "ifcommons": ("The Shambles & the Minster Yard", "York's heart — the butchers' street, the Minster, the inn and the traders."),
 "ifmilitary": ("Walmgate & the Castle", "The soldiers' quarter and Clifford's Tower, with the Tinkers' lane beside it."),
 "ifhighseat": ("The King's Manor", "Where the Council of the North sits — the Duke of Richmond's officers, and the Lord President."),
 "ifexplorers": ("The Merchant Adventurers' Hall", "The great hall of the merchants who sail to Iceland and the Baltic, full of curiosities."),
 "ifmystic": ("St Mary's Abbey", "The abbey's precinct, where the scholars and the chaplains are trained."),
 # Deeprun -> Great North Road
 "deeprun": ("The Great North Road", "London to York by the carriers' wagons — Stamford, Doncaster, and the inns between."),
 # Westfall -> Wales
 "sentinelhill": ("Ludlow Castle", "The seat of the Council of the Marches — the inn, the quartermaster, and the Lord President's command over a lawless land."),
 "saldeanfarm": ("The Teme Valley Farms", "Two farms on the river, holding out against the Marcher brotherhood."),
 "jansen": ("The Clun Stead", "A farmstead in the Clun forest, abandoned to the wolfsheads."),
 "deadacre": ("The Dead Acre & the Black Mountains", "Dead ground and the dark hills, where the brotherhood keeps its outposts."),
 "longshore": ("The Cardigan Shore & St David's Beacon", "The long western shore, the beacon on the headland, and the nixes on the sand."),
 "alexston": ("The Radnor Farmstead", "A hill farm in Radnorshire, its people fled."),
 "goldcoast": ("The Gold Streams of Dolaucothi", "The old Roman gold workings, held now by the brotherhood's miners."),
 "moonbrook": ("Rhayader, the Outlaws' Town", "A town given over to the Marcher brotherhood — no sheriff dares it."),
 "deadmines": ("The Drowned Mines of Cwmystwyth", "The brotherhood's hidden works in the old lead mine. Rhys Gethin waits at the end — an elite delve; bring friends."),
 "dmines": ("The Drowned Mines of Cwmystwyth", "The lead mine's deeps — the brotherhood's whole works, down to the chamber where Rhys Gethin sits."),
 "dustplains": ("The Desert of Wales", "The empty uplands of Elenydd — the Welsh desert, as the drovers call it."),
 # Loch Modan -> the Borders
 "thelsamar": ("Jedburgh & the Vale", "The abbey town in the Border vale — the inn, the trainers, and the Warden's men."),
 "silverstream": ("The Leadhills Silver Mine", "The silver and lead workings in the hills, overrun by kobolds."),
 "stonesplinter": ("The Teviot Crags", "Crags above the Teviot where troglodytes have come up out of the ground."),
 "theloch": ("St Mary's Loch & the Weir", "The water and the weir that holds it, and the crocodiles — so the Border folk swear — in the shallows."),
 "farstrider": ("The Hunting Lodge in Ettrick Forest", "The king of Scots' hunting forest and the lodge where the foresters meet."),
 "ironband": ("The Old Roman Camp at Newstead", "An excavation in the Roman ruins by the Tweed, troubled by troglodytes."),
 "mogrosh": ("Hermitage Castle", "The reivers' fastness in Liddesdale — Ill Will Armstrong and his riders."),
 # Wetlands -> Zeeland & Holland
 "menethil": ("Veere & the Harbour", "The Scots' staple port in Zeeland — the inn, the harbour traders, and the boats for Jutland."),
 "bluegillmarsh": ("The Biesbosch Marsh", "The drowned land of the great flood, a hundred years under water, and the nixes in it."),
 "sundownmarsh": ("The Zuider Zee Shore & the Polders", "The reclaimed fields behind the dykes, and the marsh beyond them."),
 "wreckreef": ("The Drowned Fleet of the Scheldt", "Wrecks on the sands at the river's mouth, with their drowned crews."),
 "whelgar": ("The Peat Diggings & the Frisian Tomb", "Diggers in the peat have opened an old tomb — and loosed the lynxes."),
 "dragonmaw": ("The Veluwe & the Gelder Camps", "The Duke of Guelders' raiders camped in the heath, with their beasts."),
 "dunmodr": ("Nijmegen & the Rhine Ferry", "The river town and the ferry over into the Empire."),
 # Redridge -> the Pale of Calais
 "threecorners": ("Ardres, where three roads meet", "Where the Calais road meets the French border — the watch-tower and the inn."),
 "lakeshire": ("Calais & the Pale", "The king's town over the Narrow Sea — its walls, its staple, and the Pale about it."),
 "lakeridge": ("The Guînes Road", "The road through the Pale, watched by wolfsheads."),
 "everstill": ("The Mere of Ardres", "The marsh-mere by Ardres, with its nixes and its reeds."),
 "rethban": ("The Caverns of Cap Blanc-Nez", "Caves in the chalk cliffs, full of kobolds."),
 "stonewatch": ("The Keep at Thérouanne", "The French fortress, held by the Black Bands — twenty of their champions, and the cage where the corporal is kept."),
 "ilgalar": ("The Tower at Tournehem", "A wizard's tower on the French side, where Morganth keeps his wolfsheads."),
 "rendercamp": ("The Black Bands' Camp at Boulogne", "The mercenaries' camp under the Boulonnais hills."),
 "althersmill": ("The Mill at Ardres", "A mill on the border, held by the French."),
 "stonewatchfalls": ("The Weir at Thérouanne", "The weir below the fortress, where the Black Bands wash their wounds."),
 # Duskwood -> the Ardennes
 "darkenedbank": ("The Dark Bank of the Semois", "The forest's edge, where the trees shut out the day."),
 "darkshire": ("Bouillon", "The castle town of the Ardennes — the inn, the Night Watch, and the traders."),
 "brightwood": ("Brightwood Grove", "A grove of great spiders and wood-wights."),
 "ravenhill": ("Saint-Hubert & the Stead", "The abbey of St Hubert, patron of the chase, the village, and the stead beyond — all gone quiet."),
 "vulgol": ("The Ettins' Mound", "Ettins in the hills, under a chieftain who eats what he catches."),
 "cemetery": ("The Cemetery of Saint-Hubert", "The graveyard, where the dead do not stay down."),
 "yorgen": ("The Orval Farmstead & the Southern Woods", "The abbey's farm and the woods south, full of werewolves."),
 "rolandsdoom": ("The Wolves' Cave at Han", "The cave of the werewolves under the rock at Han-sur-Lesse."),
 "forlornrowe": ("The Necromancer's Manor", "The necromancer's manor, and the thing he made from the dead."),
 # Deadwind -> Roncesvalles ; Swamp -> the Landes
 "deadwindpass": ("The Pass of Roncesvalles", "The high pass where Roland fell, under the Tower of Roland — and the dead who still guard it."),
 "harborage": ("The Pilgrims' Hospice & the Misty Valley", "The hospice on the Santiago road, kept by lost pilgrims, and the mists below it."),
 "fallowsanctuary": ("Fallow Sanctuary", "A hermits' sanctuary in the pine-moor."),
 "stonard": ("Bayonne, the French Garrison", "The French king's town at the Landes' end — enemy ground."),
 "stagalbog": ("Stagalbog & the Dragon-Murk", "The deep bog where the dragonkin lair."),
 "mistyreed": ("The Misty Reed Strand", "The reed-strand of the Arcachon basin, and its nixes."),
 "templeapproach": ("The Drowned Abbey of the Landes", "The approach to a sunk abbey in the marsh, where cultists keep the old rites."),
 "itharius": ("Itharius's Cave", "A green dragon's cave in the pine-moor."),
 "sunkentemple": ("The Drowned Abbey of the Landes", "The abbey itself, beneath the water — an elite delve to Baal-Hammon's avatar."),
 # STV -> the Barbary Shore
 "stvpath": ("The Spanish Camp at Oran & the Northern Path", "The Spanish presidio on the Barbary coast, and the path south into the Atlas."),
 "kurzencamp": ("The Renegades' Compound", "A mad colonel's deserters, gone native in the hills."),
 "nesingwary": ("The Hunting Camp", "Sir Hamnet's expedition — lions, leopards and lynx for the taking."),
 "tkashi": ("The Ruins of Tipasa", "Roman ruins on the shore, held by the Bloodscalp corsairs."),
 "nazferiti": ("Lake Fetzara", "The lake in the hills, and the corsairs camped round it."),
 "mistvale": ("The Medjerda Valley", "The river valley — apes, lions and the Skullsplitter corsairs."),
 "crystalvein": ("The Salt-Mine & the Basilisk Fields", "The salt workings, and the basilisks sunning in the fields."),
 "ziatajai": ("The Ruins of Dougga", "Roman ruins in the hills, where the corsairs keep their altars."),
 "moshogg": ("The Ettins' Mound in the Atlas", "Ettins in the mountain, and their chieftain."),
 "bootybay": ("Bougie", "The Genoese and Spanish town on the cape — a neutral port, every trade, and the corsairs kept outside the mole."),
 "wildshore": ("Cape Bon & the Wild Shore", "The cape and the wild coast beyond the port."),
 "gurubashi": ("The Ruins of Carthage & Zanzil's Dead", "The old city's ruins, and a sorcerer's walking dead among them."),
 "fleet": ("The Corsair Fleet", "Barbarossa's galleys at anchor — board them if you dare."),
 "jagueroisle": ("The Isle of the Apes", "An island off the cape, ruled by a great ape and his court."),
 "zulgurub": ("The Buried City of Carthage", "The corsairs' temple-city under the old ruins, where they raise Baal-Hammon — a raid; bring twenty."),
 # Blasted Lands -> Castile
 "nethergarde": ("The Keep at Salamanca", "The scholars' keep that watches the cave — the inn, the quartermaster, the Doctors of the university."),
 "dreadmaul": ("The Ettins' Hold at Dreadmaul", "Ettins in the red hills."),
 "redstoneflats": ("The Red-Stone Flats", "The dry red plateau, and the hyenas on it."),
 "snickerfang": ("The Snickerfang Hills", "Hyenas, basilisks and scorpions in the hills."),
 "riseofthedefiler": ("The Defiler's Rise", "A necromancer's hill, and his servants."),
 "serpentscoil": ("Serpent's Coil", "A cave of great serpents."),
 "taintedscar": ("The Tainted Scar", "The blasted ground where the devils walk — and their lord."),
 "darkportal": ("The Cave of Salamanca, the Devil's Gate", "The cave where the Devil himself kept school — and the gate at the bottom of it."),
 # Dun Morogh/Khaz Modan rest: Badlands -> Highlands; Searing Gorge -> Iceland; Burning Steppes -> Hekla
 "badlandsroad": ("The Highland Crossroads at Crieff", "Where the drove roads meet — a Lombard trader and a prospector."),
 "valleyoffangs": ("The Glen of Fangs", "A glen of dragon's teeth and the beasts that bred there."),
 "agmondsend": ("Glen Coe", "A glen of the dead, where a Dalesman's expedition ended."),
 "uldamandig": ("The Broch Diggings at Glenelg", "Diggers at the old brochs have broken into something older."),
 "angorfortress": ("Urquhart Castle", "The ruined castle on the loch, held by the Black Iron smiths."),
 "campkosh": ("The Caterans' Camps", "Highland raiders' camps in the glens."),
 "apocryphan": ("The Dragon's Rest at Glen Shiel", "A dead dragon's bones, and what feeds on them."),
 "hammertoedig": ("The Pictish Dig at Dunadd", "A dig at the old Pictish seat, troubled by troglodytes."),
 "mirageflats": ("The Flats of Rannoch", "The great moor, and the mirages on it."),
 "lethlor": ("The Great Glen of the Wyrms", "The glen where the black dragonkin nest."),
 "dustbowl": ("The Dust-Bowl at Dalwhinnie", "Dry ground and buzzards."),
 "uldaman": ("The Pictish Vault", "The vault beneath the brochs — an elite delve into the ancients' halls."),
 "thoriumpoint": ("The Smiths' Point at Hekla's Foot", "The Brotherhood of the Forge's camp under the fire-mountain — the master smith and the traders."),
 "dustfire": ("The Ash Valley of Hekla", "Ash and fire-wights in the valley."),
 "slagpit": ("The Slag Pit", "The Black Iron smiths' slave-pit."),
 "cauldron": ("The Cauldron", "The great pit where the fire-mountain's heart shows."),
 "lavapools": ("The Lava Pools", "Pools of fire, and the elementals that live in them."),
 "firewatch": ("Firewatch Ridge", "The ridge above the pools, held by cultists."),
 "hammercamps": ("The Cultists' Camps", "The Twilight's Hammer's camps on the fire-fields."),
 "morgansvigil": ("Morgan's Vigil", "The watch-camp on the fire-fells — nothing for sale but what the innkeeper and the Lombards have."),
 "dreadmaulrock": ("The Ettins' Rock", "Ettins on the rock, and the slaves they keep."),
 "terrorwing": ("Terror Wing Path", "The path of the black dragonkin."),
 "flamecrest": ("Flame Crest & the Ruins of the Black Iron City", "The Lombards' camp, and the ruins of the city the fire-mountain swallowed."),
 "pillarofash": ("The Pillar of Ash", "The Black Bands' muster under the pillar."),
 "blackrockstronghold": ("The Black Bands' Stronghold", "The mercenaries' stronghold under Hekla's shoulder."),
 "brdepths": ("The Halls beneath Hekla", "The Black Iron smiths' city under the mountain — an elite delve to their emperor."),
 "brspire": ("The Spire of Hekla", "The Black Bands' fastness on the mountain — an elite delve."),
 "moltencore": ("The Heart of Hekla, the Gate of Hell", "The fire-mountain's heart, where Surtr sits — a raid; bring forty."),
 "blackwing": ("The Lair of Níðhöggr", "The black wyrm's lair at the mountain's peak — a raid; bring forty."),
 # Lordaeron -> the Empire
 "refugepointe": ("Worms & the Refuge", "The Swabian League's camp at Worms — the inn, the smith and the traders."),
 "thandolspan": ("The Rhine Crossing at Wesel", "The bridge of boats over the Rhine, and the Black Iron smiths under it."),
 "arathiplains": ("The Palatine Plain", "Open country — lynx, lions' kin, and the robber-knights' riders."),
 "eastroad": ("The Odenwald Farm & the Road East", "The road east and a farm held by the Turk's raiders."),
 "witherbark": ("The Wild-Men's Village & the Ettins' Hall", "Wild men of the woods and ettins, uneasy neighbours."),
 "drywhisker": ("The Kobold Gorge", "Kobolds in the gorge — the German kind, who steal the miners' lamps."),
 "southridge": ("The Southern Ridge", "Ettins and stone-wights on the ridge."),
 "northfold": ("Landstuhl Castle", "Sickingen's castle, held by the robber-knights since the siege."),
 "boulderpass": ("The Northern Ettin Camps", "Ettins in the north hills."),
 "daggerspine": ("The Lorelei Reach", "The river reach under the Lorelei rock, where the melusines sing."),
 "stromgarde": ("Trifels Castle", "The old imperial castle, fallen — robber-knights, ettins and the king's last men hold its three wards."),
 "faldirscove": ("The Smugglers' Cove at Kaub", "River pirates under the toll-castle."),
 "thebindings": ("The Circles of Binding", "Stone circles where the elementals are bound."),
 "southshore": ("Konstanz", "The town on the lake — the inn, the traders, and the League's garrison."),
 "hillsbradhills": ("The Hegau Fields", "The farms under the volcanic hills — their folk no friends to strangers."),
 "westernstrand": ("The Bodensee Strand", "The lake shore, with nixes and melusines."),
 "darrowhill": ("The Hohentwiel Hill", "The great rock above the fields, and the devils' pit behind it."),
 "nethanderstead": ("The Thurgau Stead", "A farm in the Thurgau, and its werewolves."),
 "hillsbradcoast": ("The Untersee Shore & the Dalesmen's Hold", "The lower lake, and the Dalesmen's outpost at its end."),
 "durnholde": ("The Ruin of Hohenkrähen", "A robber-knights' castle, broken by the League and held again by the robbers."),
 "shadowfang": ("Burg Schattenfang", "The werewolf's castle in the dark forest — an elite delve."),
 "scarletmon": ("Reichenau Monastery", "The island monastery on the lake, held by the Scarlet Crusade — an elite delve in four wings."),
 "corrahnsdagger": ("The Horn of Uri", "A high peak and the ettins on it."),
 "yetihills": ("The Wild-Man Caves of the Jura", "Caves of the Alpine wild men."),
 "dalarancrater": ("The Fallen City's Crater & the Lake Shore", "Where the wizards' city stood, and the lake shore below it."),
 "ruinsalterac": ("The Ruins of Habsburg", "The castle the Swiss broke, and the ettins in its walls."),
 "strahnbrad": ("Brugg, the Raubritter Town", "A town given over to the robber-knights."),
 "theuplands": ("The Uplands", "High pasture and the ettins' chieftain."),
 "dandredsfold": ("The Fold at Ravenholdt", "The assassins' manor, hidden in the fold of the hills."),
 "aeriepeak": ("Innsbruck & the Eyrie", "The Tyrolean town and the griffin-riders' eyrie above it."),
 "zunwatha": ("The Wild-Men's Villages", "Two villages of the wild men of the woods."),
 "queldanil": ("The Lodge at Kufstein", "A lodge of the northern lords, keeping their own counsel."),
 "shadraalor": ("The Spider-Shrine", "The wild men's shrine to the great spider."),
 "valorwind": ("The Achensee", "The mountain lake and the ruin creeping at its edge."),
 "altarofzul": ("The Altar of the Wild Hunt", "The wild men's high altar."),
 "skulkrock": ("The Slime Rock in the Zillertal", "Oozes and the wild men's village."),
 "jinthaalor": ("The Wild-Men's Fastness on the Brenner", "The wild men's walled city on the pass — an elite climb."),
 "seradane": ("The Dragon's Hole", "The green dragons' gate in the mountain."),
 "chillwindcamp": ("The Hospitallers' Camp at Hermannstadt", "The Knights of St John's camp on the Saxons' border — the traders and the alchemist."),
 "felstonefield": ("Felstone Field", "A farm of the plague-dead."),
 "sorrowhill": ("Sorrow Hill", "The graveyard hill."),
 "dalsons": ("The Saxon Farm at Dalson", "A Saxon farm, and what is in its barn."),
 "andorhal": ("The Ruins of Szörény", "The border city the Turk broke — the plague-dead walk it."),
 "northridge": ("The Northridge Woodyard", "A lumber camp in the forest, overrun."),
 "writhinghaunt": ("The Writhing Haunt", "A haunt of the plague-dead."),
 "gahrrons": ("Gahrron's Withering", "The blighted farm and its cauldron."),
 "caerdarrow": ("The Island Fortress of Ada Kaleh", "The island in the Danube, and the ghosts of its garrison."),
 "scarletoutposts": ("The Scarlet Outposts", "The Scarlet Crusade's forward camps."),
 "hearthglen": ("Hunedoara & its Castle", "The Scarlet Crusade's seat in Corvin's castle."),
 "scholomance": ("Scholomance", "The Devil's school in the mountain, where the necromancers are taught — an elite delve."),
 "lightshope": ("The Hospitallers' Chapel at Pozsony", "The Knights of St John's chapel on the Danube — the quartermaster and the caretaker."),
 "marris": ("The Stead on the Puszta & Lake Balaton", "A dead stead on the plain and the lake beyond."),
 "darrowshire": ("The Ruins of Mohács Town", "The town the battle emptied, and its ghosts."),
 "corinscrossing": ("The Crossing at Pest", "The Danube crossing, held by the plague-dead."),
 "noxiousglade": ("The Noxious Glade", "Blighted wood and its creatures."),
 "terrordale": ("Terrordale & the Undercroft", "A dead village and the crypt under it."),
 "plaguewood": ("The Plague-Wood & the Turk's Towers", "The blighted forest, and the towers the enemy raised in it."),
 "northdale": ("Esztergom & the Archbishop's Lodge", "The archbishop's hill, and the lodge of the northern lords."),
 "tyrshand": ("Székesfehérvár, the Crusaders' Hold", "The crown city, held by the Scarlet Crusade."),
 "stratholme": ("Buda, the Fallen City", "The royal city, fallen to the enemy and the plague-dead — an elite delve."),
 "naxxramas": ("Belgrade, the Citadel of the Dead", "The enemy's great fortress on the Danube — a raid; bring forty."),
 # Northern Kalimdor: Darkshore -> Norway; Ashenvale -> Sweden; Azshara -> Gotland; Felwood -> Karelia; Winterspring -> Lapland; Moonglade -> Solovki
 "moonkinstone": ("Norway: the Runestone at Bergen", "A short sail to Bergen — where the Great Bear's test waits by the old stone."),
 "auberdine": ("Bergen & the Long Strand", "The Hanse's port under the mountains — the inn, the traders, and the long strand south."),
 "bashalaran": ("The Old Church Ruins & the Nisse Woods", "A ruined church and the woods full of nisse."),
 "ametharan": ("The Ruined Nunnery of Nonneseter", "The nuns' ruin, and the fallen sisters who walk it."),
 "longwash": ("The Hardanger Shore", "The fjord shore, with its bears and its nixes."),
 "cliffspring": ("The Voss River & the Bear-Sark Dens", "The river and the bear-sarks' dens above it."),
 "twilightvale": ("The Twilight Vale & the Giant's Skull", "A vale of cultists under a giant's skull."),
 "greymist": ("The Grey-Mist Strand & the Nix Point", "The nixes' strand in the mist."),
 "mathystra": ("Stavanger Tower & the Old Ruins", "A cultist's tower and the ruins of the old folk."),
 "maestra": ("The Watch-Post at Tiveden & the Western Road", "The watch on the great forest's road."),
 "zoram": ("The Melusine Strand at Vänern", "The lake shore where the melusines come up."),
 "astranaar": ("Örebro & the Silver Woods", "The town on its island in the river — the inn, the trainers, the silver woods about it."),
 "thistlefur": ("The Bear-Sark Village at Kolmården", "Bear-sarks in the forest."),
 "firescar": ("The Fire-Scar Shrine & the Shade Thicket", "A devils' shrine in the burnt wood."),
 "xavian": ("The Satyrs' Hollow", "Satyrs in the hollow."),
 "felfire": ("The Witch-Fire Hill & the Bear Dens", "Witch-fire on the hill and the dens below."),
 "howlingvale": ("The Howling Vale & Lake Mälaren", "Werewolves in the vale above the lake."),
 "bloodtooth": ("The Danes' Camp & the Logging Road", "The Danish king's Landsknechts, cutting the forest."),
 "blackfathom": ("The Drowned Caves of Vättern", "Caves under the lake — melusines and the cult of the Old Serpent; an elite delve."),
 "talrendis": ("Visby's Watch-Point", "The watch on Gotland's shore — a bowyer and the traders."),
 "shadowsong": ("The Ruined Shrine", "A ruined shrine of the old folk."),
 "haldarr": ("The Satyrs' Camp", "Satyrs on the heath."),
 "bearshead": ("Bear's Head", "A headland of bears."),
 "eldarath": ("The Ruins of Old Visby", "The Hanse city's broken churches, and the ghosts of its merchants."),
 "zinmalor": ("The Drowned Church", "A church half under the sea, and the melusines in it."),
 "ursolan": ("The Bear-Sarks' Den", "Bear-sarks on the north shore."),
 "lakemennar": ("The Tingstäde Mere", "The island's lake, and what lives under it."),
 "southridgebeach": ("The Southridge Strand & the Hansa Cog", "A beached Hansa cog, and its Lombard crew selling what they salvaged."),
 "thalassian": ("The Hanse's Camp", "The Lübeck men's camp on the strand."),
 "legash": ("The Devils' Camp", "A cult's camp on the heath."),
 "forlornridge": ("Forlorn Ridge", "The dragons' ridge."),
 "towereldara": ("The Powder Tower", "Visby's old tower, held by wizards."),
 "arkkoran": ("The Drowned Temple", "A temple under the sea."),
 "bayofstorms": ("The Bay of Storms", "The bay, the giants and the hydra."),
 "shatteredstrand": ("The Shattered Strand", "The broken strand at the island's end."),
 "emeraldsanctuary": ("The Hermits' Sanctuary at Valamo", "The hermits' monastery on its island in the lake — the circle's traders."),
 "felpawvillage": ("The Bear-Sark Village & the Ooze Fields", "Bear-sarks gone bad, and the fields of ooze."),
 "jadefirerun": ("The Witch-Fire Run", "Satyrs on the run."),
 "deadwoodvillage": ("The Deadwood Clearing", "Bear-sarks in the dead wood."),
 "shatterscar": ("The Shattered Vale", "Devils in the scar."),
 "irontree": ("The Iron-Tree Woods & the Cavern", "Elementals and wood-wights."),
 "deadwoodpass": ("The Deadwood Pass & the Bear-Sark Tunnel", "The pass north, and the bear-sarks' tunnel through to Lapland."),
 "jaedenar": ("The Devil-Worshippers' Hold", "The necromancers' hold in the forest."),
 "shadowhold": ("The Hold of Shadows", "The cult's deep hold — an elite delve."),
 "timbermawhold": ("The Bear-Sark Hold", "The bear-sarks' tunnel-hold between the forest and the snow — their traders."),
 "everlook": ("Tornio & the Frozen Road", "The fur market at the Baltic's head — the inn and the Lombard traders."),
 "winterfall": ("The Winterfall Camp", "Bear-sarks in the snow."),
 "keltheril": ("The Haunted Ruins at Inari", "Ruins of the old folk, and their ghosts."),
 "icethistle": ("The Ice Thistle Hills", "Wild men of the snow."),
 "owlwing": ("The Owl-Wing Thicket", "Owl-wights in the thicket."),
 "chillwind": ("The Frostfire Springs & the Chillwind Range", "Hot springs in the snow, and the range above."),
 "frostsaberrock": ("The Lynx Rock", "The snow-lynx tamers' rock."),
 "frostmaul": ("The Frost-Giants' Glacier", "The glacier where the frost-giants walk."),
 "mazthoril": ("The Ice-Wyrm's Cavern", "The blue dragons' cavern."),
 "nighthaven": ("The Solovki Monastery", "The hermits' monastery on its island in the White Sea — the circle's heart."),
 "shrineremulos": ("The Hermit's Shrine on the White Sea", "Remulos the hermit's own shrine on the island."),
 # Central Kalimdor
 "stonetalonpeak": ("Mora & the Hermits' Peak", "The town on the lake and the hermits' refuge above it — the inn and the traders."),
 "mirkfallon": ("Lake Siljan & the Spider Dens", "The lake and the spider dens."),
 "windshear": ("The Copper Mountain at Falun", "The Fuggers' company at the great copper mine."),
 "sishir": ("The Fulufjället Gorge & the Griffin Cliffs", "The gorge and the wyverns on the cliffs."),
 "charredvale": ("The Charred Vale", "The burnt vale and the harpies."),
 "grimtotem": ("The Minotaurs' Post & the Eastern Slopes", "Minotaurs on the slopes."),
 "nijelspoint": ("Kiev & the Cliff Road", "The outpost at Kiev, above the Wild Fields — the inn and the traders."),
 "kolkarvillage": ("The Nogai Camp", "A Tatar horde's camp."),
 "sartheris": ("The Dnieper Strand & the Wreck of the Venetian Galley", "The river shore and a wreck of merchants."),
 "shadowbreak": ("The Devil's Ravine", "Devils in the ravine."),
 "thunderaxe": ("The Fortress of the Burning Brotherhood", "A cult's fortress on the steppe."),
 "kodograveyard": ("The Aurochs' Graveyard", "Where the aurochs go to die."),
 "magram": ("The Azov Camp", "A Tatar horde's camp."),
 "gelkis": ("The Perekop Camp", "A Tatar horde's camp."),
 "ethelrethor": ("The Ruins of Olbia", "Greek ruins on the estuary, and the melusines."),
 "mannoroc": ("The Coven of the Wild Fields", "The devils' coven."),
 "valleyofspears": ("The Valley of Spears", "The Tatars' holy valley."),
 "maraudon": ("The Great Kurgan", "The Tatars' burial mound and the princess beneath it — an elite delve."),
 "theramore": ("Copenhagen, the King's Island", "The Danish king's island city — the inn, the traders, the Lady Joan."),
 "bloodfen": ("The Lynx Burrows of the Fen", "Lynx in the fen."),
 "darkmist": ("The Dark-Mist Cavern", "Spiders in the cave."),
 "quagmire": ("The Quagmire & Witch Hill", "The bog and the witch's hill."),
 "drywallow": ("The Drywallow Pools", "Crocodiles in the pools."),
 "sentrypoint": ("Elsinore", "The watch on the Sound — and the two caves beyond."),
 "blackshore": ("The Black Shore", "Nixes and melusines."),
 "wyrmbog": ("The Lindworm Bog", "The black dragonkin's bog."),
 "onyxia": ("The Lindworm's Lair", "The Lindorm's lair — a raid; bring forty."),
 "wailing": ("The Wailing Caves of Møn", "Caves under the cliffs — an elite delve."),
 "razorfenk": ("The Boar-Folk Hold", "The boar-men's hold — an elite delve."),
 "thalanaar": ("Perekop & the Western Steppe", "The watch at the isthmus — the traders."),
 "galakmesa": ("The Nogai Mesas", "A horde's camps on the flat-topped hills."),
 "highperch": ("The Eyrie of Chatyr-Dag", "Wyverns on the mountain."),
 "splithoof": ("The Sivash Crag & the Shallows", "Tatars and the salt shallows."),
 "shimmeringflats": ("The Sivash Salt Flats & the Horse Fair", "The salt flats, and the Lombards' and Tinkers' horse-races on them."),
 "saltscale": ("The Locust Hive on the Flats", "Locust-fiends in the salt."),
 "razorfend": ("The Boar-Folk Barrows", "The boar-men's kurgans and their dead — an elite delve."),
 "feathermoon": ("Trakai Island Castle", "The castle on its island — the inn, the trainers, the traders."),
 "verdantis": ("The Neris & the Sprite Woods", "The river and the sprite woods."),
 "solarsal": ("The Ruins of Kernavė", "The old capital's ruins, and the melusines."),
 "woodpaw": ("The Wolfshead Hills", "Wolfsheads in the hills."),
 "highwilderness": ("The High Wilderness", "The wildwood's heart."),
 "feralscar": ("The Ettins' Vale", "Ettins in the vale."),
 "writhingdeep": ("The Writhing Deep", "Locust-fiends underground."),
 "ragescar": ("Ragescar Ridge", "Ettins on the ridge."),
 "direapproach": ("The Gates of Medininkai", "The ruined city's gates, held by ettins."),
 "giantcoast": ("The Curonian Coast of the Giants", "The spit where the giantess walked, and the giants on it."),
 "isleofdread": ("Rügen, the Dread Isle", "The island of the old gods' temple."),
 "dimaul": ("Medininkai", "The ruined city — an elite delve in three wings."),
 # Southern Kalimdor: Tanaris -> Egypt; Un'Goro -> Upper Nile; Silithus -> Libya
 "gadgetzan": ("Alexandria & the Open Desert", "The Genoese and Venetian quarter of the Turk's Alexandria — the inn, the traders, the desert beyond."),
 "wastewander": ("The Wadi Natrun Oases", "Bandits at the oases."),
 "southsea": ("The Corsair Coast at Rosetta", "Corsairs on the shore."),
 "noxiouslair": ("The Locust Lair", "Locust-fiends underground."),
 "hazzali": ("Zalashji's Den & the Qattara Hives", "A melusine's den and the locust hives."),
 "dunemaul": ("The Ettins' Compound at Gizeh", "Ettins among the old tombs."),
 "thistleshrub": ("The Fayyum Thickets", "Bog-beasts in the thickets."),
 "tarpits": ("The Bitumen Pits of Gebel Zeit", "Tar and what is stuck in it."),
 "zulfarrak": ("The Road to the Mamluk Citadel", "The approach to the Mamluks' hold."),
 "gapingchasm": ("The Chasm of the Locusts", "The great hive."),
 "cavernstime": ("The Gates of Thebes", "The gates of the old kings' valley."),
 "steamwheedle": ("The Venetian Fondaco & the Dragoman's Tent", "The merchants' compound and the interpreter's tent."),
 "cavernsoftime": ("The Tombs of the Kings", "The valley of the old kings — the keepers of time."),
 "zulfarrakin": ("The Mamluk Citadel at Qena", "The Mamluks' citadel — an elite delve."),
 "marshalsrefuge": ("The Expedition's Refuge at Syene", "The explorers' camp above the cataract."),
 "goldenplain": ("The Gold Plain of Nubia", "Behemoths on the plain."),
 "fungalrock": ("Fungal Rock", "A cave of ape-men and great fungus."),
 "pylons": ("The Obelisks", "The old kings' standing stones."),
 "terrorrun": ("The Behemoth Run", "Behemoths and leviathans."),
 "fireplume": ("Fire Plume Ridge", "Fire-wights on the ridge."),
 "devilsaurrun": ("The Leviathan Run", "The leviathans' hunting ground."),
 "crystalvale": ("The Crystal Vale", "Elementals in the crystal."),
 "cenarionhold": ("Siwa Oasis & the Hermits' Hold", "The oasis of the old oracle, held by the hermits' circle — the traders."),
 "southwind": ("The Village of Bahariya", "An oasis village lost to the locust-fiends."),
 "twilightcamp": ("The Cultists' Base Camp", "The Twilight's Hammer's camp."),
 "hiveashi": ("The Locust Hive of Ashi", "A hive."),
 "twilightsrun": ("Twilight's Run & the Elemental Grounds", "The cult's road and the elementals' ground."),
 "valorsrest": ("Valor's Rest & the Diggers' Camp", "The dead and the diggers."),
 "hivezora": ("The Locust Hive of Zora", "A hive."),
 "hiveregal": ("The Locust Hive of Regal", "A hive."),
 "scarabwall": ("The Scarab Wall", "The wall before the lost city."),
 "ahnqirajgates": ("The Gates of Zerzura", "The gates of the lost oasis city."),
 "abyssalaltars": ("The Abyssal Altars", "The elementals' altars."),
 "aqruins": ("The Ruins of Zerzura", "The outer city — a raid; bring twenty."),
 "aqtemple": ("The Temple of Zerzura", "The temple of the Old Serpent — a raid; bring forty."),
}

# hub key -> town name shown in the Town tab (default: first part of the ground name)
HUB_TOWNS = {
 "shadowglen":"Whittlesey", "dolanaar":"Ramsey", "darnassus":"Ely", "northshire":"St Augustine's Abbey", "goldshire":"Ashford",
 "sentinelhill":"Ludlow", "lakeshire":"Calais", "darkshire":"Bouillon", "bootybay":"Bougie", "menethil":"Veere", "coldridge":"Reeth",
 "kharanos":"Richmond", "thelsamar":"Jedburgh", "auberdine":"Bergen", "stonetalonpeak":"Mora", "shimmeringflats":"The Horse Fair",
 "thalanaar":"Perekop", "steamwheedle":"The Venetian Fondaco", "grizzledden":"Jervaulx", "astranaar":"Örebro", "nijelspoint":"Kiev",
 "feathermoon":"Trakai", "theramore":"Copenhagen", "gadgetzan":"Alexandria", "marshalsrefuge":"The Expedition's Refuge",
 "emeraldsanctuary":"Valamo", "everlook":"Tornio", "timbermawhold":"The Bear-Sark Hold", "nighthaven":"Solovki", "swtrade":"London",
 "ifcommons":"York", "lightshope":"The Hospitallers' Chapel", "cenarionhold":"Siwa", "chillwindcamp":"Hermannstadt", "badlandsroad":"Crieff",
 "thoriumpoint":"The Smiths' Point", "morgansvigil":"Morgan's Vigil", "refugepointe":"Worms", "aeriepeak":"Innsbruck", "southshore":"Konstanz",
 "talrendis":"Visby", "southridgebeach":"The Hansa Cog", "nethergarde":"Salamanca", "harborage":"The Pilgrims' Hospice",
}
